-- Insert new wineries from "tailor moments winery database v3.xlsx"
-- Rules: insert by winery name if not already present; generate valid UUID when source winery_id is invalid.
with v (winery_id, name, region, confirmation_mode, capacity, tasting_price, description, famous_for, offers_cheese_board, unique_experience_offers, address, opening_hours, latitude, longitude, tasting_duration_minutes, website) as (
values
  ('6078e12d-886e-498c-94bf-3b67e935f457'::uuid, 'Amelia Park Wines', 'Wilyabrup', 'auto_confirm', 24, 10, '3x consecutive winner Best Cellar Door in Margaret River (Gourmet Traveller WINE). Floor-to-ceiling Wilyabrup Valley views. Award-winning restaurant. Hot contender for World''s 50 Best Vineyards 2025.', 'Cabernet Sauvignon (Jimmy Watson winner), Chardonnay, Malbec', true, '["Private Tasting Room hire", "Museum Collection seated experience", "Restaurant (seasonal estate produce)"]'::jsonb, '3857 Caves Rd, Wilyabrup WA 6280', 'Wed-Mon 10:00-17:00', -33.7824, 115.0468, 60, 'https://www.ameliaparkwines.com.au'),
  ('46efcfc5-823d-43bf-a66b-64d890ccb385'::uuid, 'Cherubino Wines', 'Cowaramup', 'manual_review', 20, 15, 'One of WA''s most awarded winemakers, Larry Cherubino. Spanish-style farmhouse cellar door with adjoining Linton & Kay Gallery (art + wine). Private barrel room and boardroom tastings.', 'Margaret River Chardonnay, Cabernet Sauvignon, Great Southern Riesling', true, '["Antipasto platters on lawn", "Barrel room tasting (up to 12)", "Boardroom private tasting (up to 20)", "Art gallery"]'::jsonb, '766 Bussell Hwy, Cowaramup WA 6284', 'Mon-Sun 10:00-17:00', -33.8365, 115.0675, 60, 'https://www.cherubinowines.com'),
  ('7207d70d-6960-442a-82a5-774f721e555d'::uuid, 'Juniper Estate', 'Wilyabrup', 'auto_confirm', 24, 10, 'Founding 1973 estate on Wilyabrup Creek. Picnic-friendly garden tasting area. Known for Cabernet and Tempranillo. Dog-friendly.', 'Cabernet Sauvignon, Tempranillo, Chardonnay', false, '["Wilyabrup Creek garden tasting area", "Picnic spot", "Dog-friendly"]'::jsonb, '98 Tom Cullity Dr, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.826, 115.049, 45, 'https://www.juniperestate.com.au'),
  ('736af952-6257-4feb-9e3f-7ddb0429aa2f'::uuid, 'Wise Wine', 'Eagle Bay', 'auto_confirm', 12, 15, '5 Red Star Halliday winery with the only ocean-view restaurant in the MR zone, overlooking both vineyard and Geographe Bay. Also features a small-batch gin and Pisco distillery.', 'Chardonnay, Cabernet Sauvignon, Eagle Bay Gin', false, '["Gin & spirits tasting (5 gins)", "Ocean-view restaurant", "Wine & gin combined experience", "Event space"]'::jsonb, 'Eagle Bay Rd, Eagle Bay WA 6281', 'Mon-Sun 10:00-17:00', -33.582, 115.027, 30, 'https://www.wisewine.com.au'),
  ('9615ea8f-70b2-4bec-a60d-16b0d936d199'::uuid, 'Flowstone Wines', 'Wilyabrup', 'auto_confirm', 20, 15, 'Boutique winery from ex-Stella Bella winemaker. Terroir-driven single-vineyard wines from exceptional WA sites. Highly regarded by trade insiders.', 'Grenache, Chardonnay, Cabernet Sauvignon', false, '["Single-vineyard comparative tasting"]'::jsonb, '9 Nash Rd, Wilyabrup WA 6280', 'Fri-Mon 11:00-17:00', -33.803, 115.058, 45, 'https://www.flowstonewines.com'),
  ('2a9bb51f-3ca0-40dc-861f-991241b5d211'::uuid, 'Peccavi Wines', 'Yallingup', 'auto_confirm', 20, 15, 'Boutique family winery on Caves Road in Yallingup. Estate-grown Cabernet, Chardonnay and Sauvignon Blanc Semillon in a welcoming environment.', 'Cabernet Sauvignon, Chardonnay, Sauvignon Blanc Semillon', false, '[]'::jsonb, '1066 Caves Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.714, 115.031, 45, 'https://www.peccaviwines.com.au'),
  ('c906cce1-db0f-4352-b9c1-f9be9c2be016'::uuid, 'Domaine Naturaliste', 'Wilyabrup', 'auto_confirm', 24, 10, 'Winemaker of the Year 2026 (Ray Jordan WA Wine Review) Bruce Dukes'' own label. Cellar door nestled right between the Merlot vines — immersive vineyard setting. Seated wine flights, cheese/charcuterie boards. Best Value Winery Australia 2020 (Halliday). Decanter Best in Show.', 'Artus Chardonnay, Rebus Cabernet Sauvignon, Morus Cabernet Sauvignon', true, '["Seated 6-wine guided flight ($25, redeemable)", "Cheese & charcuterie boards ($25, daily 11am-3pm)", "Wine Safari barrel/winery tour with 4-course lunch (seasonal)", "Music events (summer)"]'::jsonb, '160 Johnson Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.792, 115.037, 60, 'https://domainenaturaliste.com.au'),
  ('ce5171dc-0e25-4f21-90c8-23951653b6b4'::uuid, 'Lenton Brae', 'Wilyabrup', 'auto_confirm', 24, 10, 'Architecturally designed cellar door with sweeping views across Wilyabrup vines through large bay windows. On-site deli for build-your-own cheese and charcuterie platters. 38 consecutive vintages of acclaimed Semillon Sauvignon Blanc.', 'Semillon Sauvignon Blanc (38 vintages), Chardonnay, Cabernet Sauvignon', true, '["Build-your-own charcuterie platter from on-site deli", "Sweeping vineyard view tasting", "Event space", "Dog-friendly picnic area"]'::jsonb, '3887 Caves Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.802, 115.042, 60, 'https://www.lentonbrae.com'),
  ('fa2d6e0f-94f6-4644-ba91-7b2a41208725'::uuid, 'Clairault Streicker', 'Wilyabrup', 'auto_confirm', 24, 15, 'Family-owned producer making wines from four distinct vineyard sites (Clairault) and single-estate expressions (Streicker). Café-restaurant, wine blending sessions and picnic lawn.', 'Clairault Cabernet Sauvignon, Streicker Chardonnay, Sauvignon Blanc Semillon', true, '["Wine blending session", "Vineyard picnic on lawn", "Café-restaurant (casual seasonal menu)", "Dog-friendly"]'::jsonb, '3277 Caves Rd, Wilyabrup WA 6282', 'Mon-Sun 10:00-17:00', -33.76, 115.033, 45, 'https://www.clairaultstreicker.com.au'),
  ('f85a597a-45c6-4147-8042-f20358924791'::uuid, 'Flametree Wines', 'Dunsborough', 'auto_confirm', 24, 15, 'Award-winning winery in a charming beach-house-style cellar door near Dunsborough. Chardonnay and Cabernet representative of Margaret River. Hosts annual ''In Praise of Pink'' rosé festival.', 'Chardonnay, Cabernet Sauvignon, SRS (Subregional Series) range', false, '["''In Praise of Pink'' rosé festival (annual)", "Dog-friendly", "Fireplace in winter"]'::jsonb, '7 Chain Ave, Dunsborough WA 6281', 'Mon-Sun 10:00-17:00', -33.621, 115.103, 45, 'https://www.flametreewines.com'),
  ('3130a5fa-2b4e-4eca-962c-83916a64ea6a'::uuid, 'Palmer Wines', 'Dunsborough', 'auto_confirm', 24, 15, 'Founding 1977 estate just 5 minutes from Dunsborough town. Tuscan-style restaurant with lake and vineyard views. Over 50 national and international wine awards.', 'Chardonnay, Cabernet Sauvignon, Malbec', true, '["Tuscan-style restaurant (lunch Thu-Mon 11:30am-4pm", "dinner Sat from 6pm)", "Vineyard views"]'::jsonb, '1271 Caves Rd, Dunsborough WA 6281', 'Thu-Mon 10:00-17:00', -33.636, 115.073, 45, 'https://www.palmerwines.com.au'),
  ('2924b2f6-46e6-4e91-9607-00e6824271bf'::uuid, 'Redgate Wines', 'Redgate', 'auto_confirm', 24, 0, 'Founding 1977 estate — family owned and run. Known as ''the friendliest cellar door in Margaret River''. Panoramic vineyard and forest views. Bring your own picnic. Wild emus sometimes seen in the vines.', 'Cabernet Sauvignon, Chenin Blanc, Semillon Sauvignon Blanc', false, '["Picnic tables with panoramic forest and vineyard views", "Dog-friendly"]'::jsonb, 'Cnr Caves & Boodjidup Rds, Margaret River WA 6285', 'Mon-Sun 10:00-16:30', -33.99, 115.001, 30, 'https://redgatewines.com.au'),
  ('d709cafe-dd55-4cbe-bdf8-0012b44d4bed'::uuid, 'Thompson Estate', 'Wilyabrup', 'auto_confirm', 24, 0, '5 Red Star Halliday estate founded by cardiologist Dr Peter Thompson. Premium Bordeaux-style wines. Tranquil cellar door surrounded by vines with indoor and outdoor seating and vineyard views.', 'Cabernet Sauvignon, Chardonnay, Four Chambers range', false, '["Vertical tasting (same wine across multiple vintages, bookable)", "Vineyard views"]'::jsonb, '299 Tom Cullity Dr, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.813, 115.06, 45, 'https://www.thompsonestate.com.au'),
  ('3c5f2bf0-4558-49a9-929c-89d46482a31c'::uuid, 'Credaro Wines', 'Yallingup', 'auto_confirm', 24, 10, 'Four-generation family estate with a hilltop cellar door overlooking the Yallingup hills and Gunyulgup Valley. One of the best vistas of any MR cellar door. Terrace and lawn picnic available.', 'Chardonnay, Cabernet Sauvignon, Shiraz', false, '["Hilltop terrace tasting with Gunyulgup Valley views", "Picnic on lawn", "Homewares shop"]'::jsonb, '2165 Caves Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.69, 115.069, 45, 'https://www.credarofamilyestate.com.au'),
  ('f807434a-3192-4bbf-b959-d0bcc9c3d68b'::uuid, 'Snake and Herring', 'Wilyabrup', 'auto_confirm', 24, 15, 'Celebrated producer spanning Margaret River and Great Southern. Excellent restaurant on site. Known for honest, drinkable wines with a great backstory behind each label.', 'Chardonnay, Cabernet Sauvignon, Great Southern Riesling', true, '["Restaurant dining", "Dog-friendly grounds"]'::jsonb, 'Cnr Caves Rd & Harmans Mill Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.815, 115.044, 45, 'https://www.snakeandherring.com'),
  ('a5dc80fa-5be0-4d14-8d2f-26079600d1d7'::uuid, 'Woody Nook', 'Cowaramup', 'auto_confirm', 24, 10, 'Long-established boutique estate with a popular restaurant and dog-friendly event space. Consistent and well-priced wines.', 'Cabernet Sauvignon, Chardonnay, Semillon Sauvignon Blanc', false, '["Restaurant dining", "Event space", "Dog-friendly grounds"]'::jsonb, '506 Metricup Rd, Nannup WA 6280', 'Mon-Sun 10:00-17:00', -33.866, 115.107, 45, 'https://www.woodynook.com.au'),
  ('584f39f3-786f-43eb-9ef5-fc8f99a2ab0e'::uuid, 'Evans and Tate', 'Wilyabrup', 'auto_confirm', 24, 10, 'Heritage Margaret River producer established in 1970s. Approachable wines with regional character. Picnic grounds and dog-friendly setting.', 'Cabernet Sauvignon, Chardonnay, Semillon Sauvignon Blanc', false, '["Picnic spot", "Dog-friendly grounds"]'::jsonb, 'Metricup Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.78, 115.046, 45, 'https://www.evansandtate.com.au'),
  ('20c5c6d2-85dd-4b1d-86e4-d6c991e47885'::uuid, 'Happs Wines', 'Yallingup', 'auto_confirm', 24, 10, 'Pioneer estate established 1978 by Ed Happ. One of the few MR wineries with an on-site pottery studio and ceramics by the winemaker. Eclectic and characterful experience.', 'Merlot, Chardonnay, Three Hills range (rare varieties)', false, '["On-site pottery studio and art gallery", "Picnic spot", "Wedding venue"]'::jsonb, '575 Commonage Rd, Dunsborough WA 6281', 'Mon-Sun 10:00-17:00', -33.636, 115.072, 45, 'https://www.happs.com.au'),
  ('7e9cd6c3-c477-4c98-ab11-2174e7c9d97e'::uuid, 'Cape Naturaliste Vineyard', 'Yallingup', 'auto_confirm', 24, 10, 'Northernmost Margaret River estate close to Cape Naturaliste lighthouse. Outdoor tastings with vineyard views, dog-friendly. Chardonnay and Cabernet the specialities.', 'Chardonnay, Cabernet Sauvignon, Sauvignon Blanc Semillon', false, '["Outdoor vineyard tastings", "Dog-friendly", "Proximity to Cape Naturaliste lighthouse"]'::jsonb, '1 Coley Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.633, 115.03, 45, 'https://www.capernaturalistevineyard.com.au'),
  ('71cd5bf5-a5c3-4e0e-aee3-dcf0cd028f09'::uuid, 'Cape Grace Wines', 'Cowaramup', 'auto_confirm', 20, 10, 'Boutique family winery consistently earning 4.9 on DoorExplorer. Intimate, owner-operated experience in a beautiful vineyard setting. Highly personal tasting.', 'Cabernet Sauvignon, Chardonnay, Shiraz', false, '["Intimate owner-hosted tasting"]'::jsonb, '281 Cowaramup Bay Rd, Cowaramup WA 6284', 'Mon-Sun 10:00-17:00', -33.87, 115.036, 45, 'https://www.capegracewines.com.au'),
  ('b242c877-adf3-47af-8d35-e428ce47ab10'::uuid, 'Rosily Vineyard', 'Wilyabrup', 'auto_confirm', 20, 10, 'Boutique family winery with beautifully planted gardens. Intimate tasting room. Dog-friendly. Consistently excellent reviews.', 'Cabernet Sauvignon, Chardonnay, Semillon', false, '["Dog-friendly vineyard garden", "Intimate boutique tasting"]'::jsonb, '13 Yelverton Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.804, 115.072, 45, 'https://www.rosily.com.au'),
  ('2cd6435a-c90c-4346-a5b4-b408c1ed7068'::uuid, 'Victory Point Wines', 'Cowaramup', 'auto_confirm', 12, 20, 'One of Margaret River''s most awarded boutique estates. All wines are estate-grown and handcrafted. 5-star DoorExplorer rating. Tasting by appointment — exceptionally personal experience.', 'Cabernet Sauvignon (multiple trophy wins), Chardonnay', false, '["Private appointment-only tasting with owner/winemaker"]'::jsonb, 'Cnr Caves & Harmans Mill Rds, Cowaramup WA 6284', 'By appointment', -33.835, 115.07, 60, 'https://www.victorypointwines.com.au'),
  ('a863c6db-55c5-4e76-8ba3-cfb6acc2b891'::uuid, 'Walsh & Sons', 'Wilyabrup', 'auto_confirm', 24, 10, 'Family-run boutique estate. Picnic-friendly, dog-friendly. Consistent 4.9 DoorExplorer rating. Intimate and personal tasting experience.', 'Cabernet Sauvignon, Chardonnay, Semillon Sauvignon Blanc', false, '["Picnic spot", "Dog-friendly"]'::jsonb, 'Caves Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.79, 115.04, 45, 'https://www.walshandsons.com.au'),
  ('f111e12b-cd92-45fc-b7c9-fc4ce39f6ac2'::uuid, 'Driftwood Estate', 'Wilyabrup', 'auto_confirm', 24, 10, 'Popular estate known for good value wines and a relaxed, dog-friendly atmosphere. Cheese boards available. Affordable price point — great for mixed groups.', 'Cabernet Sauvignon, Chardonnay, Artefact Rosé', true, '["Cheese boards", "Dog-friendly", "Affordable wine range"]'::jsonb, '3 Chain Ave, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.78, 115.036, 45, 'https://www.driftwoodwines.com.au'),
  ('ebcedd17-6416-4e17-a4c4-796e99df985c'::uuid, 'Island Brook Estate', 'Bramley', 'auto_confirm', 24, 10, 'Boutique estate set in natural bushland with a picnic-friendly setting. Indoor tastings and a relaxed, intimate cellar door experience.', 'Cabernet Sauvignon, Chardonnay, Semillon Sauvignon Blanc', false, '["Picnic spot in natural bushland"]'::jsonb, '7 Brockman Hwy, Bramley WA 6285', 'Mon-Sun 10:00-17:00', -33.929, 115.148, 45, 'https://www.islandbrook.com.au'),
  ('7e5ea59a-edc2-4763-be24-1b80afd9c1a7'::uuid, 'MadFish Wines', 'Cowaramup', 'auto_confirm', 24, 10, 'Howard Park''s approachable label cellar door. Modern design, picnic spot, and indoor tastings with vineyard views. Great value premium wine entry point.', 'Sauvignon Blanc Semillon, Cabernet Merlot, Chardonnay', false, '["Picnic spot", "Modern design cellar door"]'::jsonb, 'Miamup Rd, Cowaramup WA 6284', 'Mon-Sun 10:00-17:00', -33.827, 115.062, 45, 'https://www.madfish.com.au'),
  ('05ca474f-0f29-4895-a746-ddfe4cdb20c1'::uuid, 'Swings & Roundabouts', 'Yallingup', 'auto_confirm', 24, 10, 'Well-established estate with two cellar doors (winery and MR township). Fireplace in winter, picnic grounds. Popular with visitors and locals. Dog-friendly.', 'Cabernet Sauvignon, Chardonnay, Backyard Series', false, '["Fireplace (winter)", "Picnic spot", "Dog-friendly", "Township cellar door option"]'::jsonb, '2807 Caves Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.678, 115.06, 45, 'https://www.swings.com.au'),
  ('790f3c81-3bb2-4c19-9ede-1c743fe0e8f4'::uuid, 'South By South West', 'Wilyabrup', 'auto_confirm', 24, 10, 'Boutique producer in Wilyabrup. Picnic-friendly, dog-friendly. Consistent reviews for approachable wines and a relaxed cellar door atmosphere.', 'Cabernet Sauvignon, Chardonnay, Sauvignon Blanc Semillon', false, '["Picnic spot", "Dog-friendly"]'::jsonb, 'Harmans Mill Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.797, 115.072, 45, 'https://www.sbswines.com.au'),
  ('a44fd2d5-80ed-49a8-a6e6-59bf5fedefd1'::uuid, 'Windance Estate', 'Yallingup', 'auto_confirm', 24, 10, 'Estate winery with on-site accommodation (chalets/cottages). Wedding and event venue. Excellent vineyard and valley views. Combines wine and retreat experience.', 'Cabernet Sauvignon, Chardonnay, Shiraz', false, '["On-site accommodation (estate chalets)", "Wedding/event venue", "Valley views"]'::jsonb, '2481 Caves Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.689, 115.063, 45, 'https://www.windance.com.au'),
  ('482a52ac-5d53-4d5d-bfd7-ac2b16088b2d'::uuid, 'Knotting Hill Estate', 'Yallingup', 'auto_confirm', 24, 10, 'Family estate in Yallingup. Dog-friendly, event space available. Relaxed cellar door setting with vineyard surroundings.', 'Cabernet Sauvignon, Chardonnay, Shiraz', false, '["Event space", "Dog-friendly"]'::jsonb, 'Caves Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.71, 115.048, 45, 'https://www.knottinghill.com.au'),
  ('46fa69a2-5a94-4963-bc68-d31d80ff4f24'::uuid, 'Jilyara Wines', 'Wilyabrup', 'auto_confirm', 16, 10, 'Ultra-boutique owner-operated estate. DoorExplorer rating 5.0 (perfect). Intimate, personal experience — one of the region''s hidden gems.', 'Cabernet Sauvignon, Chardonnay', false, '["Owner-hosted intimate tasting"]'::jsonb, 'Caves Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.793, 115.044, 45, 'https://www.jilyara.com.au'),
  ('9b3968df-43e0-4deb-a0bd-ef12b0ceecbc'::uuid, 'Montague Estate', 'Wilyabrup', 'auto_confirm', 20, 10, 'Boutique estate with outstanding DoorExplorer rating. Wheelchair accessible. Dog-friendly. Intimate boutique experience with estate wines.', 'Cabernet Sauvignon, Chardonnay, Sauvignon Blanc Semillon', false, '["Dog-friendly", "Wheelchair accessible cellar door"]'::jsonb, 'Caves Rd, Wilyabrup WA 6280', 'Mon-Sun 10:00-17:00', -33.778, 115.042, 45, 'https://www.montagueestate.com.au'),
  ('cc777946-3996-495f-936d-9111fd81fe54'::uuid, 'Rivendell Winery', 'Yallingup', 'auto_confirm', 24, 10, 'Family estate in the northern Yallingup corridor. Picnic grounds, dog-friendly, event space available. Relaxed atmosphere.', 'Cabernet Sauvignon, Chardonnay, Shiraz', false, '["Picnic spot", "Event space", "Dog-friendly grounds"]'::jsonb, '247 Wildwood Rd, Yallingup WA 6282', 'Mon-Sun 10:00-17:00', -33.652, 115.057, 45, 'https://www.rivendellwinery.com.au')
)
insert into winery (
  winery_id, name, region, confirmation_mode, capacity, active, created_at, updated_at,
  tasting_price, description, famous_for, offers_cheese_board, unique_experience_offers,
  address, opening_hours, latitude, longitude, tasting_duration_minutes, wine_styles, winery_signals, website
)
select
  v.winery_id, v.name, v.region, v.confirmation_mode, v.capacity, true, now(), now(),
  v.tasting_price, v.description, v.famous_for, v.offers_cheese_board, v.unique_experience_offers,
  v.address, v.opening_hours, v.latitude, v.longitude, v.tasting_duration_minutes,
  '[]'::jsonb, '[]'::jsonb, v.website
from v
where not exists (
  select 1 from winery w where lower(w.name) = lower(v.name)
);
