-- 026: Structured catalog for the 39 customer-selectable wineries (single source of truth).
-- Hand-reviewed mapping of legacy prospect free text into the WineStyle/WinerySignal taxonomy.
-- Generated by scripts/generate-catalog-migration.mjs.
-- USP signals (mandarin_staff, vietnamese_staff, asian_pairing, wechat_line, hosted_asian_groups,
-- exported_asia, halal, kosher, dietary) are intentionally NOT set: no source data, real collection required.

alter table winery add column if not exists catalog_featured boolean not null default false;

update winery set
  wine_styles = '["Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","winery_lunch","vineyard_walk","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Cabernet & Chardonnay'),
  description = coalesce(nullif(description, ''), 'Margaret River''s founding winery (est. 1967), celebrated for its Art of Cabernet and Chardonnay, with a vine-to-table epicurean lunch tour.'),
  updated_at = now()
where winery_id = '11111111-1111-1111-1111-111111111111'; -- Vasse Felix

update winery set
  wine_styles = '["Organic & Biodynamic","White Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","vineyard_walk","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Kevin John Chardonnay'),
  description = coalesce(nullif(description, ''), 'Biodynamic pioneers (est. 1971) known for the iconic Kevin John Chardonnay and a biodynamic spiral garden tour.'),
  updated_at = now()
where winery_id = '22222222-2222-2222-2222-222222222222'; -- Cullen Wines

update winery set
  wine_styles = '["Red Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","barrel_tasting","cellar_tour","vineyard_walk"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Bordeaux-style reds'),
  description = coalesce(nullif(description, ''), 'Bordeaux-style elegance from the Parterre vineyard, with an electric-buggy vineyard and barrel tour.'),
  updated_at = now()
where winery_id = '33333333-3333-3333-3333-333333333333'; -- Fraser Gallop

update winery set
  wine_styles = '["Red Wine Specialist","Organic & Biodynamic","Estate-grown fruit only"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","seated_tasting","guided_tasting","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Heritage Cabernet'),
  description = coalesce(nullif(description, ''), 'Dry-grown vines and elegant heritage Cabernets (est. 1973), with seated vertical museum tastings.'),
  updated_at = now()
where winery_id = '44444444-4444-4444-4444-444444444444'; -- Woodlands

update winery set
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention","Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","intimate_welcome","garden_picnic","small_production"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Low-intervention small batch'),
  description = coalesce(nullif(description, ''), 'Compost-focused, low-intervention small-batch wines with intimate garden-side tastings.'),
  updated_at = now()
where winery_id = '6be3229f-dc8c-8265-b76f-a0fa486fa504'; -- Stormflower

update winery set
  wine_styles = '["Organic & Biodynamic","Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","cellar_tour","guided_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Artisan basket-press wines'),
  description = coalesce(nullif(description, ''), 'Artisan basket-press methods with a soil focus, offering a behind-the-scenes Grape to Glass tour.'),
  updated_at = now()
where winery_id = '99889e7f-0541-3e5e-9cc9-a0219ec9dcdd'; -- Windows Estate

update winery set
  wine_styles = '["White Wine Specialist","Well known Margaret River Name","Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","vineyard_walk","intimate_welcome","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Elite Chardonnay'),
  description = coalesce(nullif(description, ''), 'Elite Burgundian-style Chardonnay (est. 1979), with personalised Friday vineyard tours.'),
  updated_at = now()
where winery_id = '786a007c-6447-c792-1c2d-c7eedcb1c80e'; -- Pierro

update winery set
  wine_styles = '["Family-owned Estate"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","multi_generation","historic_estate","intimate_welcome"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Multi-generational family wines'),
  description = coalesce(nullif(description, ''), 'Multi-generational family estate (est. 1975) with a mud-brick cellar door and traditional guided tastings.'),
  updated_at = now()
where winery_id = 'af6a0bbf-f27a-5a9c-5d10-5123a1e4665b'; -- Ashbrook Estate

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","winery_lunch","charcuterie_board","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Rustico tapas pairing'),
  description = coalesce(nullif(description, ''), 'Set around a historic hay shed (est. 1973), known for Rustico tapas and wine pairing lunches.'),
  updated_at = now()
where winery_id = 'd5df22ab-333e-2eed-e6e1-0c46091d5198'; -- Hayshed Hill

update winery set
  wine_styles = '["Red Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","seated_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'World-class Cabernet'),
  description = coalesce(nullif(description, ''), 'Wilyabrup ''sweet spot'' estate making world-class Cabernet, with seated Reserve tastings.'),
  updated_at = now()
where winery_id = '83a42af6-841d-a94d-07b9-83bb07c1d443'; -- Fermoy Estate

update winery set
  wine_styles = '["Fortified & Dessert Wines","Well known Margaret River Name","Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","historic_estate","guided_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Famous fortifieds'),
  description = coalesce(nullif(description, ''), 'The region''s first cellar door (est. 1975), famous for fortifieds and premium vertical museum flights.'),
  updated_at = now()
where winery_id = '6878ef0b-b794-39dc-dfec-d6d7200d28e7'; -- Gralyn Estate

update winery set
  wine_styles = '["Estate-grown fruit only","Small batch & Boutique","Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","barrel_tasting","cellar_tour"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'High-density terroir'),
  description = coalesce(nullif(description, ''), 'High-density 1m x 1m plantings for pure terroir, with a behind-the-scenes barrel room tour.'),
  updated_at = now()
where winery_id = 'b1222f17-4b74-754c-fa56-5a5bfc96a463'; -- Menzies Vineyard

update winery set
  wine_styles = '["Organic & Biodynamic","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","winery_lunch","vineyard_walk","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Manicured gardens & degustation'),
  description = coalesce(nullif(description, ''), 'Cape Dutch-style estate famous for manicured gardens, offering a 7-course degustation and garden walk.'),
  updated_at = now()
where winery_id = '81c43507-fd2d-866e-7ce9-b3697ef1bb75'; -- Voyager Estate

update winery set
  wine_styles = '["Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","press_featured","corporate_events","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Art Series & concerts'),
  description = coalesce(nullif(description, ''), 'World-famous Art Series labels and concerts (est. 1973), with wine and art gallery pairing flights.'),
  updated_at = now()
where winery_id = '8023295f-0fda-e61e-8ff9-cf418ffe0f7d'; -- Leeuwin Estate

update winery set
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","historic_estate","corporate_events"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Iconic Cabernet'),
  description = coalesce(nullif(description, ''), 'SBS pioneers with iconic Cabernet heritage (est. 1970) and seasonal Movies in the Vineyard.'),
  updated_at = now()
where winery_id = 'bf7e6df5-5101-2569-ee7f-489c107f935e'; -- Cape Mentelle

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Suckfizzle'),
  description = coalesce(nullif(description, ''), 'Southern cool-climate elegance, known for Suckfizzle and horizontal tasting sessions.'),
  updated_at = now()
where winery_id = '7097c5db-283a-6e0e-58ad-abd598d233e9'; -- Stella Bella

update winery set
  wine_styles = '["Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","trophy_winner","guided_tasting","historic_estate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Consistent trophy winner'),
  description = coalesce(nullif(description, ''), 'A consistent trophy winner with a modern rustic vibe and Cellar Collective museum sessions.'),
  updated_at = now()
where winery_id = '0220379d-36c2-41b8-34e2-762538e27955'; -- Xanadu Wines

update winery set
  wine_styles = '["Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","charcuterie_board","guided_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Italian-soul handcraft'),
  description = coalesce(nullif(description, ''), 'Traditional hand-craft wines with an Italian soul, paired with curated tastings and local grazing boards.'),
  updated_at = now()
where winery_id = 'c22cbb53-a339-8a7b-6115-3128656645ce'; -- Mr. Barval

update winery set
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","cellar_tour","intimate_welcome"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Authentic rustic wines'),
  description = coalesce(nullif(description, ''), 'Unpretentious, authentic rustic wines with winemaker-led private tours.'),
  updated_at = now()
where winery_id = 'd1239ea2-d792-43c7-06b1-dd65a8b5e269'; -- Yeah Wine

update winery set
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention","Estate-grown fruit only"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","winery_lunch","vineyard_walk"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Single-vineyard mastery'),
  description = coalesce(nullif(description, ''), 'Single-vineyard, low-intervention wines with a vintner''s lunch and biodiversity walks.'),
  updated_at = now()
where winery_id = '773a08da-f201-c484-853b-cc5e693bcd5e'; -- McHenry Hohnen

update winery set
  wine_styles = '["White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","view_stunning","seated_tasting","guided_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Elite Chardonnay'),
  description = coalesce(nullif(description, ''), 'Ridge-top views and elite Chardonnay, with Reserve horizontal deck tastings.'),
  updated_at = now()
where winery_id = 'de8c34be-f131-04ad-2fbd-3013cfbd396b'; -- Deep Woods

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","winery_lunch","corporate_events"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Luxury estate & car museum'),
  description = coalesce(nullif(description, ''), 'A luxury estate with a Sports Car Museum, offering a car museum and wine high tea.'),
  updated_at = now()
where winery_id = 'd83fd6d2-8bdd-989f-53e2-4e4d641d6f71'; -- Aravina Estate

update winery set
  wine_styles = '["Red Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","winery_lunch"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Paladin Shiraz & fine dining'),
  description = coalesce(nullif(description, ''), 'Fine-dining focus and the flagship Paladin Shiraz, with a 4-course chef''s selection lunch.'),
  updated_at = now()
where winery_id = '5c8e4e4b-601e-70f2-3c90-3eb9bcacbf3d'; -- Wills Domain

update winery set
  wine_styles = '["Natural & Minimal Intervention","Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","vineyard_walk"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Radical natural wines'),
  description = coalesce(nullif(description, ''), 'Radical natural winemaking from eco-pioneers, with a wild wine and bee-keeping farm tour.'),
  updated_at = now()
where winery_id = '017d1fc8-1afd-10bd-1b80-0f751c7a3085'; -- Blind Corner

update winery set
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","secluded","intimate_welcome","vineyard_walk"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Biodynamic forest vineyard'),
  description = coalesce(nullif(description, ''), 'A biodynamic forest vineyard with beach vibes and forest-side personalised tastings.'),
  updated_at = now()
where winery_id = '5d5bd129-3b5e-bb49-6605-6a6098ba8c72'; -- Marri Wood Park

update winery set
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique","Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","cheese_board"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Lo-Fi young wines'),
  description = coalesce(nullif(description, ''), 'Funky ''Lo-Fi'' young wines, with Green Room cheese and wine sessions.'),
  updated_at = now()
where winery_id = '82dc2053-1d49-5227-9f95-7274a025727a'; -- Skigh Wine

update winery set
  wine_styles = '["White Wine Specialist","Sparkling & Method traditionnelle Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Riesling & sparkling'),
  description = coalesce(nullif(description, ''), 'Modern architecture and a focus on Riesling and bubbles, with Methode Traditionnelle masterclasses.'),
  updated_at = now()
where winery_id = '67b423d3-54e3-48fa-3357-6b29bc976ccd'; -- Howard Park

update winery set
  wine_styles = '["Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","intimate_welcome","vineyard_walk","secluded"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Wildlife sanctuary wines'),
  description = coalesce(nullif(description, ''), 'A highly personal estate with a wildlife sanctuary focus and a Nature & Wine wildlife walk.'),
  updated_at = now()
where winery_id = '8d99b646-1362-04a2-9efb-b2e4a0fbbae8'; -- Passel Estate

update winery set
  wine_styles = '["Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","wine_chocolate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Organic award-winning labels'),
  description = coalesce(nullif(description, ''), 'Organic methods and award-winning labels, with The Full Hand chocolate and wine flight.'),
  updated_at = now()
where winery_id = 'd1bf0d17-ae35-b32c-7f8a-be3b7ff4c043'; -- House of Cards

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","view_stunning","wine_chocolate"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Wine & nougat pairing'),
  description = coalesce(nullif(description, ''), 'Known for wine and world-class nougat pairing in a lakeside setting.'),
  updated_at = now()
where winery_id = '31378e5f-07d1-217b-36e6-af243908afda'; -- Bettenay''s

update winery set
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","blending_experience"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Experimental funky wines'),
  description = coalesce(nullif(description, ''), 'Experimental, high-energy wines with a hands-on School of Winemaking.'),
  updated_at = now()
where winery_id = 'e831283e-09c2-eaca-e1f3-c2f4f1f41308'; -- LS Merchants

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","seated_tasting"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Aviation-themed cellar door'),
  description = coalesce(nullif(description, ''), 'Aviation-themed estate with a Tiger Moth plane on site and a seated ''Wings'' room flight.'),
  updated_at = now()
where winery_id = 'b4e8b6a2-851b-de47-31f3-68e53a0494e9'; -- Edwards Wines

update winery set
  wine_styles = '["Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","picnic_on_estate","vineyard_walk"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), '16 organic varietals'),
  description = coalesce(nullif(description, ''), 'Organically operated across 16 varietals, with self-guided organic vineyard picnics.'),
  updated_at = now()
where winery_id = '75208f29-0dc6-1580-78e6-9aa982e6a4a9'; -- Churchview

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","wheelchair_access","charcuterie_board","corporate_events"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Accessible large-format venue'),
  description = coalesce(nullif(description, ''), 'A highly accessible, large-format venue offering regional produce platter experiences.'),
  updated_at = now()
where winery_id = '36716a04-29bc-98e3-1fcd-f2e7602e02e7'; -- 3 Oceans

update winery set
  wine_styles = '["Red Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","barrel_tasting","private_tasting_room"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Bold reds'),
  description = coalesce(nullif(description, ''), 'Bold reds and barrel-hall experiences, with private Barrel Room tastings.'),
  updated_at = now()
where winery_id = 'fa2f4f97-b0f9-2886-4ad6-6711ab28781d'; -- Brown Hill

update winery set
  wine_styles = '["Natural & Minimal Intervention","Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","intimate_welcome"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Zero-intervention natural wines'),
  description = coalesce(nullif(description, ''), 'Natural-farming, zero-intervention wines via by-appointment winemaker sessions.'),
  updated_at = now()
where winery_id = '49e41adf-d8bc-e9ef-9158-f33022a104ce'; -- Si Vintners

update winery set
  wine_styles = '["Organic & Biodynamic"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","winery_lunch","vineyard_walk"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Farm-to-table'),
  description = coalesce(nullif(description, ''), 'Farm-to-table with sheep and vines, offering a Ground to Glass foragers tour.'),
  updated_at = now()
where winery_id = 'c60a5b7c-8a29-51e8-4c23-0a945033ad64'; -- Glenarty Road

update winery set
  wine_styles = '[]'::jsonb,
  winery_signals = '["cellar_door_tasting","view_stunning","seated_tasting","winery_lunch","charcuterie_board"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Valley & lake views'),
  description = coalesce(nullif(description, ''), 'Coastal-influenced wines with valley and lake views, and a seated deck platter and wine lunch.'),
  updated_at = now()
where winery_id = 'bc30ab2c-95ed-c658-29dd-6d74521e7184'; -- Hamelin Bay

update winery set
  wine_styles = '["Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","halliday_5star","barrel_tasting","intimate_welcome","small_production"]'::jsonb,
  catalog_featured = true,
  famous_for = coalesce(nullif(famous_for, ''), 'Boutique 5-star'),
  description = coalesce(nullif(description, ''), 'Boutique 5-star, small-batch focus with barrel tasting alongside the owner.'),
  updated_at = now()
where winery_id = '1b5e3afb-da62-c8a2-c13c-f259f5c1039d'; -- Evoi Wines

