-- 028: Populate the 39 featured wineries from official-website scraping + AI extraction.
-- Generated by scripts/generate-scrape-migration.mjs. wine_styles/winery_signals validated
-- against the taxonomy; tasting prices >50 or missing defaulted to 15; website only adopted
-- from real official sites. All rows data_verified=false for winery self-review on signup.

update winery set
  wine_styles = '["Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting"]'::jsonb,
  tasting_price = 15,
  description = '3 Oceans is a major winemaking operation in Margaret River celebrating Western Australia''s dramatic coastline and pristine environment. Their cellar door offers a curated selection of single-vineyard and regional wines.',
  famous_for = 'Chardonnay and Shiraz from the Margaret River region',
  website = 'https://www.3oceanswine.com.au',
  data_source_url = 'https://www.3oceanswine.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = '36716a04-29bc-98e3-1fcd-f2e7602e02e7'; -- 3 Oceans

update winery set
  wine_styles = '["Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["quiet_space","cellar_door_tasting","trophy_winner","gold_medals","multi_generation"]'::jsonb,
  tasting_price = 15,
  description = 'A family-owned estate in Wilyabrup operating for over 40 years, Ashbrook produces elegant, handcrafted varietal wines using sustainable vineyard practices. Renowned for understated quality and exceptional value, the winery runs a quiet cellar door focused on premium wine experiences.',
  famous_for = 'Elegant premium wines; James Halliday recognition',
  website = 'https://www.ashbrookwines.com.au',
  data_source_url = 'https://www.ashbrookwines.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = 'af6a0bbf-f27a-5a9c-5d10-5123a1e4665b'; -- Ashbrook Estate

update winery set
  wine_styles = '["Red Wine Specialist","Family-owned Estate","Estate-grown fruit only","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","cellar_door_tasting","guided_tasting","garden_picnic","wine_chocolate","charcuterie_board","winery_lunch","accommodation","private_tasting_room","sunset_tasting","seated_tasting","dog_friendly","child_friendly","gold_medals","trophy_winner","multi_generation"]'::jsonb,
  tasting_price = 25,
  description = 'Established in 1989 by the Bettenay family in Cowaramup, this boutique estate produces premium Cabernet Sauvignon, Chardonnay and Shiraz alongside its renowned hand-crafted nougat. Guests enjoy a distinctive cellar door experience paired with lakeside dining and on-site accommodation.',
  famous_for = 'Premium wines and decadent hand-crafted nougat',
  opening_hours = '7 days, 10am-5pm',
  data_source_url = 'https://bettenaysmargaretriver.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '31378e5f-07d1-217b-36e6-af243908afda'; -- Bettenay''s

update winery set
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention","White Wine Specialist","Red Wine Specialist","Sparkling & Method traditionnelle Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","small_production","certified_organic","regenerative","garden_picnic","vineyard_walk"]'::jsonb,
  tasting_price = 15,
  description = 'A certified organic and biodynamic winery in Yallingup with 20 years of heritage, Blind Corner crafts naturally made wines using old-world techniques with new-world innovation. Their cellar door welcomes visitors to taste biodynamically grown wines beside the working vineyard.',
  famous_for = 'Certified organic and biodynamic natural wines',
  website = 'https://www.blindcorner.com.au',
  data_source_url = 'https://www.blindcorner.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = '017d1fc8-1afd-10bd-1b80-0f751c7a3085'; -- Blind Corner

update winery set
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","vineyard_walk"]'::jsonb,
  tasting_price = 15,
  description = 'Cape Mentelle is a pioneering Margaret River winery established in the early 1970s, known for terroir-driven wines of exceptional quality and consistency. The estate welcomes visitors to its cellar door for tastings and tours of its acclaimed vineyard.',
  famous_for = 'Benchmark Cabernet Sauvignon and Shiraz',
  website = 'https://www.capementelle.com.au',
  data_source_url = 'https://www.capementelle.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = 'bf7e6df5-5101-2569-ee7f-489c107f935e'; -- Cape Mentelle

update winery set
  wine_styles = '["Organic & Biodynamic","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","garden_picnic","cellar_door_tasting","charcuterie_board","picnic_on_estate","wine_chocolate","certified_organic"]'::jsonb,
  tasting_price = 15,
  description = 'Churchview Estate is a family-owned organic winery in Metricup, established in 1999, growing 16 grape varieties across 100 hectares. The cellar door offers tastings of premium, rare wines paired with optional ploughman''s lunches or picnics overlooking the vineyards.',
  famous_for = 'Certified organic wines, especially Chardonnay',
  opening_hours = 'Mon-Sat 10:00-17:00, closed Sun',
  website = 'https://www.churchview.com.au',
  data_source_url = 'https://www.churchview.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '75208f29-0dc6-1580-78e6-9aa982e6a4a9'; -- Churchview

update winery set
  wine_styles = '["Organic & Biodynamic","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","historic_estate","multi_generation","view_stunning","certified_organic","gold_medals","intimate_welcome"]'::jsonb,
  tasting_price = 15,
  description = 'A premier biodynamic and organic winery in Wilyabrup, founded in 1971 and now in its third generation under Vanya Cullen. Cullen produces award-winning wines with a focus on exceptional Cabernet Sauvignon and Chardonnay, crafted through certified biodynamic viticulture.',
  famous_for = 'Biodynamic, award-winning Cabernet Sauvignon and Chardonnay',
  website = 'https://www.cullenwines.com.au',
  data_source_url = 'https://www.cullenwines.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = '22222222-2222-2222-2222-222222222222'; -- Cullen Wines

update winery set
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Small batch & Boutique","Estate-grown fruit only","Well known Margaret River Name","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","secluded","garden_picnic","cellar_door_tasting","guided_tasting","seated_tasting","halliday_5star","gold_medals","trophy_winner","multi_generation"]'::jsonb,
  tasting_price = 15,
  description = 'An award-winning Margaret River estate perched on a ridge above a secluded valley of native jarrah and marri. Deep Woods produces acclaimed Cabernet Sauvignon, Reserve Chardonnay and Rose, poured in a modern cellar door set in a stunning natural setting.',
  famous_for = 'Cabernet, Chardonnay and Rose; Halliday Five Red Star',
  opening_hours = '7 days 10:30-17:00',
  website = 'https://www.deepwoods.wine',
  data_source_url = 'https://www.deepwoods.wine',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'de8c34be-f131-04ad-2fbd-3013cfbd396b'; -- Deep Woods

update winery set
  wine_styles = '["Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","multi_generation"]'::jsonb,
  tasting_price = 15,
  description = 'Edwards Wines is a hand-crafted Margaret River winery in Cowaramup where quality wines are paired with a warm family story. The cellar door welcomes guests daily for attentive service and tastings in a distinctive setting.',
  famous_for = 'Hand-crafted quality wines with family heritage',
  opening_hours = '10:30-17:00 daily',
  website = 'https://www.edwardswines.com.au',
  data_source_url = 'https://www.edwardswines.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'b4e8b6a2-851b-de47-31f3-68e53a0494e9'; -- Edwards Wines

update winery set
  wine_styles = '["Well known Margaret River Name","Small batch & Boutique"]'::jsonb,
  winery_signals = '["halliday_5star","cellar_door_tasting","guided_tasting","intimate_welcome","small_production"]'::jsonb,
  tasting_price = 15,
  description = 'An acclaimed boutique Margaret River winery holding a James Halliday 5-star rating and named a Western Australian Winery of the Year. Visitors enjoy premium cellar-door tastings in a small-batch estate known for excellence.',
  famous_for = 'Halliday 5-star wines; WA Winery of the Year',
  website = 'https://www.evoiwines.com',
  data_source_url = 'https://www.evoiwines.com',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = '1b5e3afb-da62-c8a2-c13c-f259f5c1039d'; -- Evoi Wines

update winery set
  wine_styles = '["Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Estate-grown fruit only","Small batch & Boutique"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","wine_chocolate","charcuterie_board","dog_friendly","garden_picnic","picnic_on_estate","seated_tasting","accommodation","private_tasting_room","barrel_tasting","winery_lunch","intimate_welcome","close_to_town","gold_medals","multi_generation","regenerative"]'::jsonb,
  tasting_price = 15,
  description = 'Fermoy Estate is a family-owned Wilyabrup winery established in 1985, crafting refined Cabernet Sauvignon and Chardonnay with a philosophy of precision and elegance. The cellar door offers guided tastings and seasonal small bites, indoors or in the vineyard gardens.',
  famous_for = 'World-class Cabernet Sauvignon',
  opening_hours = '11:00-17:00 daily',
  website = 'https://www.fermoy.com.au',
  data_source_url = 'https://www.fermoy.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '83a42af6-841d-a94d-07b9-83bb07c1d443'; -- Fermoy Estate

update winery set
  wine_styles = '["Red Wine Specialist","Estate-grown fruit only","Small batch & Boutique","Family-owned Estate","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","view_stunning","dog_friendly","halliday_5star","gold_medals","intimate_welcome"]'::jsonb,
  tasting_price = 15,
  description = 'Fraser Gallop Estate is a Halliday 5-star Wilyabrup winery producing exceptional single-vineyard wines with a focus on precision and purity. The intimate cellar door welcomes guests daily to taste award-winning Cabernet Sauvignon and Chardonnay overlooking the vineyard.',
  famous_for = 'Cabernet Sauvignon; Decanter Best in Show; Halliday 5-star',
  opening_hours = 'Daily 11:00-16:00',
  website = 'https://www.frasergallopestate.com.au',
  data_source_url = 'https://www.frasergallopestate.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '33333333-3333-3333-3333-333333333333'; -- Fraser Gallop

update winery set
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Natural & Minimal Intervention","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","garden_picnic","dog_friendly","vineyard_walk","cellar_tour","winery_lunch","charcuterie_board","picnic_on_estate","intimate_welcome","secluded","vegetarian","multi_generation","regenerative","press_featured"]'::jsonb,
  tasting_price = 35,
  description = 'Glenarty Road is a fifth-generation family farm in Karridale where premium minimal-intervention wines and farm-to-table dining thrive across 81 hectares of regeneratively managed land. Guests enjoy cellar-door tastings alongside seasonal cuisine from estate-grown produce and grass-fed meats in a rustic farmhouse setting.',
  famous_for = 'Farm-to-table dining and minimal-intervention wines; award-winning regional restaurant',
  opening_hours = 'Wed-Mon 10:00-17:00',
  website = 'https://www.glenartyroad.com.au',
  data_source_url = 'https://www.glenartyroad.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'c60a5b7c-8a29-51e8-4c23-0a945033ad64'; -- Glenarty Road

update winery set
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Fortified & Dessert Wines","Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","Internationally awarded"]'::jsonb,
  winery_signals = '["historic_estate","cellar_door_tasting","private_tasting_room","guided_tasting","barrel_tasting","multi_generation","trophy_winner","gold_medals"]'::jsonb,
  tasting_price = 15,
  description = 'Gralyn Estate is a family-owned Wilyabrup winery established in 1975, now in its second generation, renowned for premium estate wines and exceptional fortifieds from mature, non-irrigated vines. Visitors explore the cellar door with tastings of celebrated Chardonnay, Cabernet and award-winning fortified wines.',
  famous_for = 'Famous fortifieds; premium Cabernet and Chardonnay',
  opening_hours = 'Daily 10:30-16:30',
  website = 'https://gralyn.com.au',
  data_source_url = 'https://gralyn.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '6878ef0b-b794-39dc-dfec-d6d7200d28e7'; -- Gralyn Estate

update winery set
  wine_styles = '["Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","cellar_door_tasting","guided_tasting","winery_lunch","cheese_board","charcuterie_board","child_friendly","seated_tasting","quiet_space","gold_medals","multi_generation"]'::jsonb,
  tasting_price = 15,
  description = 'Established in 1992 by the Drake-Brockman family, Hamelin Bay is a boutique Karridale winery producing elegant whites and structured reds from gravelly loam soils. The estate sits on a north-facing ridge with panoramic vineyard, valley and karri-forest views, with a welcoming cellar door and on-site restaurant.',
  famous_for = 'Award-winning estate wines and scenic cellar-door dining',
  opening_hours = 'Daily 10:30-16:30',
  website = 'https://hbwines.com.au',
  data_source_url = 'https://hbwines.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'bc30ab2c-95ed-c658-29dd-6d74521e7184'; -- Hamelin Bay

update winery set
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","seated_tasting","guided_tasting","blending_experience","wine_chocolate","dog_friendly","halliday_5star","view_stunning"]'::jsonb,
  tasting_price = 15,
  description = 'One of Margaret River''s pioneering wineries, Hayshed Hill offers a beautiful cellar door for seated tastings of an extensive range of wines. The intimate setting is the perfect backdrop to explore renowned Chardonnays and Cabernet blends with vineyard views.',
  famous_for = 'Premium Chardonnay and Cabernet; 20-vintage winemaking legacy',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://hayshedhill.com.au',
  data_source_url = 'https://hayshedhill.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'd5df22ab-333e-2eed-e6e1-0c46091d5198'; -- Hayshed Hill

update winery set
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name","Estate-grown fruit only"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","winery_lunch","garden_picnic","view_stunning","seated_tasting","vegetarian","vegan","gluten_free","corporate_events"]'::jsonb,
  tasting_price = 15,
  description = 'Aravina Estate is a Margaret River winery and destination restaurant in Yallingup, established in 2010, combining award-winning wines with fine dining. The estate features a cellar door for tastings, modern Australian cuisine, manicured gardens and a renowned sports car museum.',
  famous_for = 'Award-winning wines, garden-to-table dining and a sports car museum',
  opening_hours = 'Daily 10:00-17:00',
  data_source_url = null,
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = 'd83fd6d2-8bdd-989f-53e2-4e4d641d6f71'; -- Aravina Estate

update winery set
  wine_styles = '["Red Wine Specialist","Estate-grown fruit only","Family-owned Estate","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["cellar_door_tasting","intimate_welcome","guided_tasting","close_to_town","barrel_tasting"]'::jsonb,
  tasting_price = 15,
  description = 'Brown Hill Estate is a family-owned Margaret River winery where all fruit is hand-picked and hand-sorted at harvest. Visitors enjoy tastings in a welcoming cellar door open daily, in a warm family setting that celebrates the estate''s journey from bare paddock to premium wines.',
  famous_for = 'Bold red wines, particularly Cabernet Sauvignon',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://www.brownhillestate.com.au',
  data_source_url = 'https://www.brownhillestate.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'fa2f4f97-b0f9-2886-4ad6-6711ab28781d'; -- Brown Hill

update winery set
  wine_styles = '["Organic & Biodynamic","Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["intimate_welcome","secluded","cellar_door_tasting","garden_picnic","dog_friendly","child_friendly","accommodation","cheese_board","seated_tasting","quiet_space","certified_organic","small_production"]'::jsonb,
  tasting_price = 15,
  description = 'House of Cards is a certified-organic, single-vineyard winery where Elizabeth and Travis Wray craft handmade wines using traditional methods like hand-plunging and basket pressing. Visitors enjoy intimate tastings and local cheese platters at a relaxed cellar door overlooking the natural landscape.',
  famous_for = 'Certified-organic single-vineyard, hand-crafted wines',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://www.houseofcardswine.com.au',
  data_source_url = 'https://www.houseofcardswine.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'd1bf0d17-ae35-b32c-7f8a-be3b7ff4c043'; -- House of Cards

update winery set
  wine_styles = '["Sparkling & Method traditionnelle Specialist","Well known Margaret River Name","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","garden_picnic","historic_estate","halliday_5star","gold_medals","seated_tasting","vineyard_walk"]'::jsonb,
  tasting_price = 15,
  description = 'Howard Park is an acclaimed Margaret River estate spanning 138 hectares of vines and native bushland near Cowaramup. The architecturally striking cellar door welcomes visitors to taste award-winning wines, with spacious lawns ideal for a picnic.',
  famous_for = 'Award-winning sparkling and premium estate wines',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://howardparkwines.com.au',
  data_source_url = 'https://howardparkwines.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '67b423d3-54e3-48fa-3357-6b29bc976ccd'; -- Howard Park

update winery set
  wine_styles = '["Small batch & Boutique","Natural & Minimal Intervention","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","dog_friendly","child_friendly","seated_tasting","vineyard_walk","garden_picnic","corporate_events","wedding_venue","blending_experience"]'::jsonb,
  tasting_price = 15,
  description = 'LS Merchants is a handcrafted boutique winery (founded 2015) embracing minimal-intervention winemaking across diverse South West varietals. Their Cowaramup cellar door offers seated tastings overlooking the vineyard, balancing premium classics with experimental, approachable wines.',
  famous_for = 'Clean, expressive minimal-intervention wines; award-winning Chardonnay',
  opening_hours = 'Daily 10:30-16:30',
  website = 'https://www.lsmerchants.com.au',
  data_source_url = 'https://www.lsmerchants.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'e831283e-09c2-eaca-e1f3-c2f4f1f41308'; -- LS Merchants

update winery set
  wine_styles = '["Organic & Biodynamic","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Sparkling & Method traditionnelle Specialist"]'::jsonb,
  winery_signals = '["secluded","cellar_door_tasting","guided_tasting","dog_friendly","child_friendly","intimate_welcome","garden_picnic","quiet_space","cheese_board","vineyard_walk","cellar_tour","certified_organic","regenerative"]'::jsonb,
  tasting_price = 0,
  description = 'A family-owned Demeter-certified biodynamic vineyard established in 1992, Marri Wood Park crafts pure expressions of Margaret River terroir using chemical-free practices. Visitors retreat to an intimate rustic cellar door in native bushland for tastings of biodynamic wines, from lively sparkling to serious estate reds.',
  famous_for = 'Demeter-certified biodynamic wines, especially Sparkling Chenin Blanc',
  opening_hours = 'Wed-Sun 11:00-15:00',
  website = 'https://marriwoodpark.com.au',
  data_source_url = 'https://marriwoodpark.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '5d5bd129-3b5e-bb49-6605-6a6098ba8c72'; -- Marri Wood Park

update winery set
  wine_styles = '["Organic & Biodynamic","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","winery_lunch","cheese_board","garden_picnic","seated_tasting","certified_organic","regenerative","small_production","vegetarian","wine_chocolate"]'::jsonb,
  tasting_price = 15,
  description = 'A biodynamically certified estate in Margaret River''s south producing minimal-intervention, single-vineyard wines that express place. The expanded Witchcliffe cellar door pairs guided tastings with seasonal Mediterranean cuisine and a Vintners wine bar sourced from estate farms.',
  famous_for = 'Biodynamic single-vineyard wines',
  opening_hours = 'Daily 10:30-16:30',
  website = 'https://www.mchenryhohnen.com.au',
  data_source_url = 'https://www.mchenryhohnen.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '773a08da-f201-c484-853b-cc5e693bcd5e'; -- McHenry Hohnen

update winery set
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","intimate_welcome","vineyard_walk"]'::jsonb,
  tasting_price = 15,
  description = 'A family-owned Wilyabrup winery featuring one of Australia''s rare high-density vineyards, with vines planted at four times standard density to deepen terroir expression. Rob and Emma Menzies welcome visitors to an intimate cellar door for hand-picked, organically grown wines.',
  famous_for = 'High-density vineyard and organic, hand-crafted wines',
  website = 'https://menziesvineyard.com.au',
  data_source_url = 'https://menziesvineyard.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = 'b1222f17-4b74-754c-fa56-5a5bfc96a463'; -- Menzies Vineyard

update winery set
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","barrel_tasting","winery_lunch","cheese_board","charcuterie_board","vineyard_walk","intimate_welcome","multi_generation"]'::jsonb,
  tasting_price = 15,
  description = 'Mr Barval is a boutique Margaret River winery founded by Robert Gherardi, drawing on three generations of family winemaking and Italian techniques from Barolo. The cellar door welcomes visitors daily for Italian-inspired wines paired with local cheeses and artisanal condiments.',
  famous_for = 'Italian-influenced Margaret River wines',
  opening_hours = 'Daily 11:00-17:00',
  website = 'https://mrbarval.com',
  data_source_url = 'https://mrbarval.com',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'c22cbb53-a339-8a7b-6115-3128656645ce'; -- Mr. Barval

update winery set
  wine_styles = '["Small batch & Boutique","Estate-grown fruit only","Red Wine Specialist","Sparkling & Method traditionnelle Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["garden_picnic","dog_friendly","cellar_door_tasting","guided_tasting","seated_tasting","vineyard_walk","charcuterie_board","gold_medals","trophy_winner","halliday_5star","small_production","regenerative"]'::jsonb,
  tasting_price = 15,
  description = 'A family-owned boutique winery in a Margaret River bushland setting, crafting small-batch wines while stewarding a native flora sanctuary. The cellar door invites visitors to taste premium Shiraz, Cabernet and Chardonnay while supporting conservation of the endangered Western Ringtail Possum.',
  famous_for = 'Trophy-winning sparkling and small-batch reds; conservation focus',
  opening_hours = 'Daily 10:30-17:00',
  website = 'https://www.passelestate.com',
  data_source_url = 'https://www.passelestate.com',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '8d99b646-1362-04a2-9efb-b2e4a0fbbae8'; -- Passel Estate

update winery set
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","White Wine Specialist","Red Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["intimate_welcome","secluded","dog_friendly","cellar_door_tasting","quiet_space","vineyard_walk"]'::jsonb,
  tasting_price = 0,
  description = 'Pierro is a boutique Wilyabrup estate founded in 1979 by Dr Michael Peterkin, known for unconventional high-density viticulture and uncompromising winemaking. It produces stylish, complex whites and exceptional reds, poured at an intimate rammed-earth cellar door set among the vines with creek views.',
  famous_for = 'Cult-status Chardonnay of monumental weight and texture',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://www.pierro.com.au',
  data_source_url = 'https://www.pierro.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '786a007c-6447-c792-1c2d-c7eedcb1c80e'; -- Pierro

update winery set
  wine_styles = '["Natural & Minimal Intervention","Organic & Biodynamic","Estate-grown fruit only","Small batch & Boutique","Family-owned Estate"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","small_production","female_winemaker","dog_friendly","wedding_venue","corporate_events"]'::jsonb,
  tasting_price = 15,
  description = 'Si Vintners is a biodynamically certified Margaret River estate in Rosa Glen, dedicated to minimal-intervention winemaking from its own dry-grown vines. Founded by Sarah Morris and Iwo Jakimowicz, it produces distinctive natural wines, welcoming visitors by appointment for cellar-door tastings.',
  famous_for = 'Biodynamic, minimal-intervention natural wines; skin-contact styles',
  opening_hours = 'Fri-Sat 11:00-16:00 (by appointment)',
  website = 'https://sivintners.com',
  data_source_url = 'https://sivintners.com',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '49e41adf-d8bc-e9ef-9158-f33022a104ce'; -- Si Vintners

update winery set
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique","Estate-grown fruit only","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["intimate_welcome","garden_picnic","cellar_door_tasting","guided_tasting","quiet_space","small_production","vegan","cheese_board"]'::jsonb,
  tasting_price = 15,
  description = 'Skigh Wine is an intimate boutique minimal-intervention winery set among Yallingup''s gardens, making small-batch natural wines that showcase Margaret River fruit with old-world flair. The rustic barn cellar door offers personalised tastings across its classic, Coda and experimental ranges in a laid-back setting.',
  famous_for = 'Minimal-intervention natural wines with wild ferments',
  opening_hours = 'Daily 10:30-17:00',
  website = 'https://www.skighwine.com.au',
  data_source_url = 'https://www.skighwine.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '82dc2053-1d49-5227-9f95-7274a025727a'; -- Skigh Wine

update winery set
  wine_styles = '["Well known Margaret River Name","Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","guided_tasting","picnic_on_estate","dog_friendly","child_friendly","close_to_town","garden_picnic","quiet_space","gold_medals","trophy_winner"]'::jsonb,
  tasting_price = 10,
  description = 'A boutique Margaret River winery producing wines of elegant finesse and precision from the region''s pristine southern terroir. The cellar door, just minutes from town, invites visitors to experience an award-winning portfolio in a charming, unpretentious vineyard setting.',
  famous_for = 'Premium Chardonnay and Cabernet; the Suckfizzle range',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://www.stellabella.com.au',
  data_source_url = 'https://www.stellabella.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '7097c5db-283a-6e0e-58ad-abd598d233e9'; -- Stella Bella

update winery set
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention","Small batch & Boutique","Estate-grown fruit only","Sparkling & Method traditionnelle Specialist"]'::jsonb,
  winery_signals = '["intimate_welcome","cellar_door_tasting","picnic_on_estate","vineyard_walk","certified_organic","small_production","garden_picnic"]'::jsonb,
  tasting_price = 15,
  description = 'Stormflower is a boutique certified-organic winery in Wilyabrup producing elegant, handcrafted wines entirely from estate-grown fruit. Visitors enjoy a relaxed, naturally designed cellar door and can unwind with a picnic rug in the gardens, surrounded by nine hectares of sustainably managed vineyard.',
  famous_for = 'Certified-organic, minimal-intervention wines and sparkling',
  opening_hours = 'Thu-Mon 11:00-17:00',
  website = 'https://stormflower.com.au',
  data_source_url = 'https://stormflower.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '6be3229f-dc8c-8265-b76f-a0fa486fa504'; -- Stormflower

update winery set
  wine_styles = '["Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Sparkling & Method traditionnelle Specialist","Estate-grown fruit only","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","guided_tasting","seated_tasting","winery_lunch","cheese_board","charcuterie_board","wedding_venue","corporate_events","dog_friendly","halliday_5star","gold_medals","press_featured","historic_estate"]'::jsonb,
  tasting_price = 15,
  description = 'Wills Domain is a prestigious estate on 60 hectares of sun-drenched slopes in Yallingup''s Gunyulgup Valley, with sweeping views across vine-covered hills. The cellar door pairs exceptional estate-grown wines with curated snacks, alongside an acclaimed fine-dining restaurant in an unforgettable vineyard setting.',
  famous_for = 'Cabernet, Shiraz and sparkling; award-winning restaurant',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://willsdomain.com.au',
  data_source_url = 'https://willsdomain.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '5c8e4e4b-601e-70f2-3c90-3eb9bcacbf3d'; -- Wills Domain

update winery set
  wine_styles = '["Organic & Biodynamic","Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","private_tasting_room","picnic_on_estate","vineyard_walk","cellar_tour","certified_organic","garden_picnic","intimate_welcome","vegetarian","vegan","charcuterie_board"]'::jsonb,
  tasting_price = 15,
  description = 'A boutique Margaret River winery owned by Chris and Joanne Davies, regarded as one of the region''s most exciting producers. The cellar door welcomes visitors daily for curated tastings and gourmet picnics on the manicured lawn or by the vineyard dam.',
  famous_for = 'Certified-organic, hand-crafted wines and private picnic tastings',
  opening_hours = 'Thu-Tue 10:00-17:00',
  website = 'https://www.windowsestate.com',
  data_source_url = 'https://www.windowsestate.com',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '99889e7f-0541-3e5e-9cc9-a0219ec9dcdd'; -- Windows Estate

update winery set
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Organic & Biodynamic","Estate-grown fruit only","Well known Margaret River Name","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","seated_tasting","guided_tasting","cheese_board","charcuterie_board","dog_friendly","child_friendly","garden_picnic","intimate_welcome","gold_medals","multi_generation","certified_organic"]'::jsonb,
  tasting_price = 0,
  description = 'Established in 1973, Woodlands is one of Margaret River''s pioneering wineries, crafting premium wines from certified-organic vineyards in the Wilyabrup Valley. The cellar door welcomes visitors for hand-picked, traditionally made wines in a warm, family-friendly setting with seated tastings and gourmet cheese platters.',
  famous_for = 'Heritage Cabernet Sauvignon and Chardonnay from dry-grown vines',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://woodlandswines.com.au',
  data_source_url = 'https://woodlandswines.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '44444444-4444-4444-4444-444444444444'; -- Woodlands

update winery set
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name","Estate-grown fruit only","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","guided_tasting","private_tasting_room","winery_lunch","cheese_board","charcuterie_board","vineyard_walk","cellar_tour","wedding_venue","seated_tasting","wheelchair_access","gold_medals","trophy_winner","close_to_town"]'::jsonb,
  tasting_price = 30,
  description = 'Xanadu is a pioneering Margaret River estate established in 1977, set among stunning vineyard views with a tranquil courtyard. A minimalist winemaking philosophy expresses the region''s true character, with a cellar door and fine-dining restaurant showcasing globally awarded Cabernet Sauvignon and Chardonnay.',
  famous_for = 'International award-winning Cabernet Sauvignon and Chardonnay',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://xanaduwines.com',
  data_source_url = 'https://xanaduwines.com',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '0220379d-36c2-41b8-34e2-762538e27955'; -- Xanadu Wines

update winery set
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["dog_friendly","child_friendly","cellar_door_tasting","small_production","vegan"]'::jsonb,
  tasting_price = 15,
  description = 'Yeah Wine is a Margaret River producer crafting handmade, small-batch wines that showcase the personality of single-vineyard sources. Founded in 2020 by Andrew Dawson and Sian, the cellar door welcomes families and dogs in a warm, approachable setting for natural, experimental wines.',
  famous_for = 'Lesser-known varieties and natural winemaking',
  opening_hours = 'Daily 10:30-17:00',
  website = 'https://www.yeahwine.com.au',
  data_source_url = 'https://www.yeahwine.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = 'd1239ea2-d792-43c7-06b1-dd65a8b5e269'; -- Yeah Wine

update winery set
  wine_styles = '["Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","seated_tasting","guided_tasting","winery_lunch","wine_chocolate","vineyard_walk","garden_picnic","intimate_welcome","historic_estate","gold_medals","trophy_winner","press_featured"]'::jsonb,
  tasting_price = 15,
  description = 'Leeuwin Estate is a renowned Margaret River producer devoted to the art of fine wine, set amid rolling lawns and karri forest. The cellar door offers seated tastings in an art-gallery setting, complemented by an acclaimed restaurant and the celebrated Leeuwin Concert series.',
  famous_for = 'Art Series Chardonnay and Cabernet; the Leeuwin Concerts',
  opening_hours = 'Daily 10:00-17:00',
  website = 'https://www.leeuwinestate.com.au',
  data_source_url = 'https://www.leeuwinestate.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '8023295f-0fda-e61e-8ff9-cf418ffe0f7d'; -- Leeuwin Estate

update winery set
  wine_styles = '["Natural & Minimal Intervention","Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist"]'::jsonb,
  winery_signals = '["historic_estate","cellar_door_tasting","guided_tasting","winery_lunch","vineyard_walk","cellar_tour","multi_generation"]'::jsonb,
  tasting_price = 15,
  description = 'Vasse Felix is Margaret River''s founding wine estate (established 1967), offering a premium cellar-door experience of estate-grown wines made with minimal intervention. Visitors enjoy tastings, fine dining, art installations and guided vineyard tours across the Home Vineyard overlooking Wilyabrup Brook.',
  famous_for = 'Cabernet Sauvignon and Chardonnay; the region''s founding winery',
  website = 'https://www.vassefelix.com.au',
  data_source_url = 'https://www.vassefelix.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'high',
  data_verified = false,
  updated_at = now()
where winery_id = '11111111-1111-1111-1111-111111111111'; -- Vasse Felix

update winery set
  wine_styles = '["Estate-grown fruit only","Organic & Biodynamic","Well known Margaret River Name","Red Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","winery_lunch","vineyard_walk","cellar_tour","garden_picnic","certified_organic","historic_estate","wedding_venue","corporate_events","gold_medals"]'::jsonb,
  tasting_price = 15,
  description = 'Voyager Estate is a Margaret River winery built on generations of farming heritage, where certified-organic viticulture and sustainable practices shape every bottle. Visitors experience estate-grown wines, manicured Cape Dutch gardens, a seasonal restaurant and immersive vineyard experiences.',
  famous_for = 'Cabernet Sauvignon and manicured gardens',
  website = 'https://www.voyagerestate.com.au',
  data_source_url = 'https://www.voyagerestate.com.au',
  data_scraped_at = '2026-06-14T06:14:44.940Z',
  data_confidence = 'medium',
  data_verified = false,
  updated_at = now()
where winery_id = '81c43507-fd2d-866e-7ce9-b3697ef1bb75'; -- Voyager Estate

