-- 030_winery_scrape.sql
-- Phase 2: website-scraped visit signals for the 39 featured wineries.
-- Generated by scripts/build-scrape-migration.mjs from scrape-results.json.
-- Signals are MERGED (union) with existing data; USP/language/religious signals excluded.

BEGIN;

-- 3 Oceans  (confidence: medium; +15 signals)
UPDATE winery SET
  wine_styles = '["Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","winery_lunch","cheese_board","child_friendly","corporate_events","vegetarian","gluten_free","wheelchair_access","accessible_parking","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = '3 Oceans is a family estate in the Margaret River region producing a small range of wines (the Explorers and Lost Dogs ranges) from its own vineyards in Margaret River and Frankland River. The large Cowaramup venue (the former Palandri winery) houses a cellar door and a family-friendly winery cafe, and hosts live music events through the year.',
  famous_for = 'A large cellar door and winery cafe (known for its "Wine Platter for two") alongside its own Explorers and Lost Dogs estate wine ranges.',
  opening_hours = 'Cellar Door 10am-5pm; cafe Breakfast 9-11:30am, Lunch 12-3pm, daily (excluding Christmas, New Year & Good Friday) per third-party listings. The winery''s own website does not state hours.',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.3oceanswine.com.au',
  updated_at = now()
WHERE winery_id = '36716a04-29bc-98e3-1fcd-f2e7602e02e7';

-- Aravina Estate  (confidence: medium; +14 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name","Estate-grown fruit only","Family-owned Estate"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","winery_lunch","garden_picnic","view_stunning","seated_tasting","vegetarian","vegan","gluten_free","corporate_events","cheese_board","child_friendly","wheelchair_access","accessible_parking","minibus_parking","minibus_access","wedding_venue","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Aravina Estate is a family-run Margaret River winery near Yallingup with a cellar door, sit-down restaurant overlooking the lake and vineyards, and its own 8 Waves Brewing Co. taphouse. Cellar door staff guide visitors through a tasting of six estate-grown wines, with the option of a tasting matched to a multi-course meal.',
  famous_for = 'Estate-grown wines paired with lakeside vineyard dining and an on-site craft brewery and surf gallery.',
  opening_hours = 'Cellar door / restaurant: Mon-Tue 11am-4pm, Wed-Sun 11am-5pm; food service 11:30am-3pm daily. Open 7 days, closed Dec 25 & 26.',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.aravinaestate.com.au',
  updated_at = now()
WHERE winery_id = 'd83fd6d2-8bdd-989f-53e2-4e4d641d6f71';

-- Ashbrook Estate  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["quiet_space","cellar_door_tasting","trophy_winner","gold_medals","multi_generation","guided_tasting","garden_picnic","press_featured","mon","tue","wed","thu","fri","sat"]'::jsonb,
  description = 'A quiet, family-owned and operated estate at Wilyabrup running for over 40 consecutive vintages, offering relaxed, guided cellar door tastings of premium handcrafted single-vineyard wines from 100% estate-grown fruit. Picnic facilities are available on site.',
  famous_for = 'Elegant, understated estate-grown Margaret River whites (Riesling, Semillon, Sauvignon Blanc, Verdelho, Chardonnay) and trophy-winning wines praised by James Halliday.',
  opening_hours = 'Cellar sales and tasting open 11.00am - 4.00pm Monday to Saturday. Closed Good Friday, Christmas Day, Boxing Day and New Year''s Day.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.ashbrookwines.com.au',
  updated_at = now()
WHERE winery_id = 'af6a0bbf-f27a-5a9c-5d10-5123a1e4665b';

-- Bettenay's  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","Family-owned Estate","Estate-grown fruit only","Internationally awarded","Natural & Minimal Intervention","Small batch & Boutique","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","cellar_door_tasting","guided_tasting","garden_picnic","wine_chocolate","charcuterie_board","winery_lunch","accommodation","private_tasting_room","sunset_tasting","seated_tasting","dog_friendly","child_friendly","gold_medals","trophy_winner","multi_generation","cheese_board","small_production","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'A family-owned single-vineyard estate established by Greg and Terri Bettenay in 1989, Bettenays pairs premium wines made with minimum intervention alongside its famous Margaret River nougat, all produced onsite. Visitors can enjoy complimentary nougat tastings with a viewing window into the nougat kitchen, plus a lakeside bistro for lunch.',
  famous_for = 'Their famous Margaret River nougat (all produced onsite) paired with estate wines',
  opening_hours = 'Cellar door open 7 days a week 10am - 5pm (closed Christmas Day). Lakeside Bistro 11am - 3pm: 2 or 3 course chef-select menu Fri-Sun; specials board and platters Mon-Thu.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://bettenaysmargaretriver.com.au/',
  updated_at = now()
WHERE winery_id = '31378e5f-07d1-217b-36e6-af243908afda';

-- Blind Corner  (confidence: medium; +9 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention","White Wine Specialist","Red Wine Specialist","Sparkling & Method traditionnelle Specialist","Small batch & Boutique","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","small_production","certified_organic","regenerative","garden_picnic","vineyard_walk","view_stunning","dog_friendly","child_friendly","seated_tasting","tue","wed","thu","fri","sat"]'::jsonb,
  description = 'Blind Corner is a certified Organic and Biodynamic family winery in Quindalup (Margaret River''s northern end), started 20 years ago by Ben and Naomi Gould, making minimal-intervention wines including sparkling, white, orange/skin-contact, red and preservative-free styles. Their seasonal Bar Nature is a casual, family- and dog-friendly wine and beer haven with vineyard views toward the Yallingup ridge, pouring organic wines and small-batch organic beer brewed on site alongside snacks.',
  famous_for = 'Certified Organic and Biodynamic, minimal-intervention ''natural'' wines and regenerative farming, with an on-site microbrewery and the casual Bar Nature cellar door.',
  opening_hours = 'Seasonal — Bar Nature open summer (Dec until Easter). Stated trading hours: Tuesday-Saturday 11-5pm (closed Sundays & Mondays); Bar Nature opening listed 11am-6pm daily over peak summer. Closed to the public outside the summer season / by appointment.',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.blindcorner.com.au',
  updated_at = now()
WHERE winery_id = '017d1fc8-1afd-10bd-1b80-0f751c7a3085';

-- Brown Hill  (confidence: high; +12 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","Estate-grown fruit only","Family-owned Estate","Well known Margaret River Name","Small batch & Boutique","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","intimate_welcome","guided_tasting","close_to_town","barrel_tasting","seated_tasting","private_tasting_room","multi_generation","small_production","no_food","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Brown Hill Estate is a boutique, family-owned winery in Rosa Brook, run hands-on by the Bailey family from a rustic green-shed cellar door built inside the working winery, so visitors can watch winemaking happen year-round. Seated tastings are guided by a family member through the estate''s three ranges of handpicked, hand-sorted, estate-grown wines.',
  famous_for = 'Affordable, quality red wines (shiraz and cabernet) from a single estate vineyard, with wines named after famous Kalgoorlie gold mines',
  opening_hours = 'Open 7 days a week, 10am-5pm',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.brownhillestate.com.au/',
  updated_at = now()
WHERE winery_id = 'fa2f4f97-b0f9-2886-4ad6-6711ab28781d';

-- Cape Mentelle  (confidence: medium; +13 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name","Internationally awarded","Estate-grown fruit only"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","vineyard_walk","historic_estate","garden_picnic","private_tasting_room","cellar_tour","trophy_winner","close_to_town","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Cape Mentelle is a pioneering Margaret River cellar door at 331 Wallcliffe Road, open daily, with a relaxed garden setting offering swings, picnic tables and traditional French petanque lanes. Tastings range from a tasting-room experience to a private walking tour through the winemaking process ending in the rammed-earth Cabernet Cellar with a tutored wine and food pairing.',
  famous_for = 'A founding Margaret River winery known for its benchmark Cabernet Sauvignon (Jimmy Watson Trophy winner)',
  opening_hours = 'Cellar door open daily 10am - 5pm',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.capementelle.com.au/',
  updated_at = now()
WHERE winery_id = 'bf7e6df5-5101-2569-ee7f-489c107f935e';

-- Churchview  (confidence: high; +14 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Well known Margaret River Name","Small batch & Boutique","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","garden_picnic","cellar_door_tasting","charcuterie_board","picnic_on_estate","wine_chocolate","certified_organic","historic_estate","dog_friendly","guided_tasting","seated_tasting","cheese_board","byo_food","multi_generation","small_production","mon","tue","wed","thu","fri","sat"]'::jsonb,
  description = 'Churchview Estate is a boutique, family-owned, certified-organic single vineyard at Metricup, where you taste through rare and premium wines in a heritage period cottage looking out over the vines. Built from the ground up in 1999 by father-and-son Spike and Raymond Fokkema, it grows 16 varieties across 56 hectares of estate vineyard.',
  famous_for = 'Certified-organic, estate-grown single-vineyard wines tasted in a heritage period cottage named for the nearby St Johns Anglican Church',
  opening_hours = 'Open Monday to Saturday, 10am-5pm',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.churchview.com.au',
  updated_at = now()
WHERE winery_id = '75208f29-0dc6-1580-78e6-9aa982e6a4a9';

-- Cullen Wines  (confidence: high; +15 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded","Family-owned Estate"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","historic_estate","multi_generation","view_stunning","certified_organic","gold_medals","intimate_welcome","seated_tasting","private_tasting_room","winery_lunch","vineyard_walk","vegetarian","gluten_free","regenerative","female_winemaker","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Family-owned, third-generation biodynamic and carbon-neutral estate founded in 1971, where seated tastings of estate Cabernet Sauvignon and Chardonnay take place in the Biodynamic Wine Room. Over 90% of the restaurant''s set-menu ingredients are grown in their on-site biodynamic garden.',
  famous_for = 'Pioneering biodynamic Margaret River winemaking and its iconic Diana Madeline (Cabernet) and Kevin John (Chardonnay) wines.',
  opening_hours = 'Wine tastings 10:00am - 4.30pm, 7 days a week (cellar door). Restaurant operates select days/seasons.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.cullenwines.com.au',
  updated_at = now()
WHERE winery_id = '22222222-2222-2222-2222-222222222222';

-- Deep Woods  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Small batch & Boutique","Estate-grown fruit only","Well known Margaret River Name","Internationally awarded","Family-owned Estate"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","secluded","garden_picnic","cellar_door_tasting","guided_tasting","seated_tasting","halliday_5star","gold_medals","trophy_winner","multi_generation","byo_food","cheese_board","press_featured","mon","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Operating since 1987 amid the jarrah and marri forests of Yallingup, Deep Woods Estate offers relaxed tastings of its award-winning wines, with guests welcome to bring their own picnic to enjoy on the lawn with a glass of estate wine. Led by celebrated chief winemaker Julian Langworthy, it is renowned for its Reserve Chardonnay and Cabernet Sauvignon.',
  famous_for = 'Award-winning Reserve Chardonnay and Cabernet Sauvignon, and being one of Western Australia''s most decorated wineries (chief winemaker Julian Langworthy, 2019 Halliday Australian Winemaker of the Year)',
  opening_hours = 'Cellar door open six days a week from 10.00am to 5.00pm; closed Tuesdays. Open on WA public holidays falling on a Monday; closed Good Friday, Anzac Day, Christmas Day, Boxing Day, New Year''s Day. (The cellar-door page instead states open seven days 10.30am-5pm; the dedicated opening-hours page is treated as authoritative.)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.deepwoods.wine',
  updated_at = now()
WHERE winery_id = 'de8c34be-f131-04ad-2fbd-3013cfbd396b';

-- Edwards Wines  (confidence: high; +14 signals)
UPDATE winery SET
  wine_styles = '["Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Well known Margaret River Name","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","multi_generation","intimate_welcome","wheelchair_access","dog_friendly","winery_lunch","wine_chocolate","private_tasting_room","small_production","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Family-owned and operated since 1991, Edwards Wines pours estate-grown wines daily at its Cowaramup cellar door, where the restored 1943 Tiger Moth ''Matilda'' takes pride of place. Visitors can taste alongside gourmet local platters or a handmade chocolate pairing, with an on-site restaurant, Miss Chow''s, overlooking the vines.',
  famous_for = 'Estate-grown hand-crafted wines and the Matilda Tiger Moth story; founder Brian Edwards'' historic flight from England to Australia.',
  opening_hours = 'Open daily 10:30am - 5pm',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.edwardswines.com.au',
  updated_at = now()
WHERE winery_id = 'b4e8b6a2-851b-de47-31f3-68e53a0494e9';

-- Evoi Wines  (confidence: medium; +7 signals)
UPDATE winery SET
  wine_styles = '["Well known Margaret River Name","Small batch & Boutique","White Wine Specialist","Internationally awarded","Wines only available at cellar door"]'::jsonb,
  winery_signals = '["halliday_5star","cellar_door_tasting","guided_tasting","intimate_welcome","small_production","cellar_tour","child_friendly","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Evoi Wines is a boutique Margaret River winery at 529 Osmington Rd, Bramley, founded in 2007 by hands-on winemaker Nigel Ludlow, who began with two barrels of Chardonnay. The cellar door sits on a working vineyard with expansive lawns and children''s play equipment, and pours small batch Reserve wines available only on site.',
  famous_for = 'Boutique, Chardonnay-focused wines from a 5 Red Star Halliday-rated winery; named Western Australian Winery of the Year at the 2015 Melbourne International Wine Show and recognised in Gourmet Traveller''s Cellar Door Awards.',
  opening_hours = '"Opening Hours are 10.00am to 5.00pm, Wednesday to Sunday." (visit page; site home/listings also state 10am-5pm)',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.evoiwines.com',
  updated_at = now()
WHERE winery_id = '1b5e3afb-da62-c8a2-c13c-f259f5c1039d';

-- Fermoy Estate  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Estate-grown fruit only","Small batch & Boutique","Family-owned Estate","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","wine_chocolate","charcuterie_board","dog_friendly","garden_picnic","picnic_on_estate","seated_tasting","accommodation","private_tasting_room","barrel_tasting","winery_lunch","intimate_welcome","close_to_town","gold_medals","multi_generation","regenerative","trophy_winner","press_featured","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Family-owned estate established in 1985 in Wilyabrup, Margaret River, with a 14-hectare estate vineyard, offering relaxed guided cellar door tastings of up to five wines at $15 per guest. The dog-friendly cellar door pours wines by the glass alongside local grazing, with a summer seasonal bistro (Elliott''s at Fermoy) and on-site accommodation at The Lodge.',
  famous_for = 'Cabernet Sauvignon and Chardonnay; its Reserve Cabernet Sauvignon won Decanter World Wine Awards ''Best in Show'' (2024) and ''Platinum'' (2025).',
  opening_hours = 'Open daily, 11am-5pm (closed Good Friday, Christmas Day & Boxing Day)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.fermoy.com.au',
  updated_at = now()
WHERE winery_id = '83a42af6-841d-a94d-07b9-83bb07c1d443';

-- Fraser Gallop  (confidence: high; +16 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","Estate-grown fruit only","Small batch & Boutique","Family-owned Estate","Internationally awarded","Well known Margaret River Name","White Wine Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","view_stunning","dog_friendly","halliday_5star","gold_medals","intimate_welcome","vineyard_walk","cellar_tour","cheese_board","wedding_venue","corporate_events","trophy_winner","small_production","female_winemaker","multi_generation","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Founded in 1999 by Nigel Gallop in Margaret River''s Wilyabrup valley, Fraser Gallop Estate is a single-vineyard, dry-farmed estate making precise, estate-grown wines under winemaker Ellin Tritt. The cellar door offers curated tastings daily, plus a seasonal Wines & Vines Tour exploring the gardens and vineyard blocks by solar-powered buggy with a cheese platter.',
  famous_for = 'Single-vineyard, estate-grown Wilyabrup wines prized for precision and purity, including the Parterre Chardonnay (Decanter World Wine Awards Best in Show) and Palladian Cabernet Sauvignon, with a 5-Star James Halliday rating.',
  opening_hours = 'Cellar door open daily from 11am to 4pm (closed on some public holidays). Tasting fees apply, fully redeemable on purchase.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.frasergallopestate.com.au',
  updated_at = now()
WHERE winery_id = '33333333-3333-3333-3333-333333333333';

-- Glenarty Road  (confidence: high; +12 signals)
UPDATE winery SET
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Natural & Minimal Intervention","Red Wine Specialist","White Wine Specialist","Lesser known (off the beaten track)","Sparkling & Method traditionnelle Specialist"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","garden_picnic","dog_friendly","vineyard_walk","cellar_tour","winery_lunch","charcuterie_board","picnic_on_estate","intimate_welcome","secluded","vegetarian","multi_generation","regenerative","press_featured","historic_estate","seated_tasting","cheese_board","child_friendly","gluten_free","small_production","wed","thu","fri","sat","sun","mon"]'::jsonb,
  description = 'Glenarty Road is a five-generation family farm in Karridale (southern Margaret River) offering paddock-to-plate dining, estate-grown wines made with a hands-off, natural approach, and a wine bar serving house-made charcuterie, cheese and freshly baked bread. Experiences range from a $15 traditional tasting to garden walks, regenerative farm tours, and a roaming vino-in-the-vines feast.',
  famous_for = 'Farm-to-table regenerative dining — named Australia''s Best Destination Dining (Gourmet Traveller, 2023)',
  opening_hours = 'Wine bar 10am-5pm Wednesday to Monday (closed Tuesday); grazing snacks 11:30am-2:30pm; restaurant 11:30am-2:30pm Wednesday to Monday',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.glenartyroad.com.au/',
  updated_at = now()
WHERE winery_id = 'c60a5b7c-8a29-51e8-4c23-0a945033ad64';

-- Gralyn Estate  (confidence: high; +17 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Fortified & Dessert Wines","Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","Internationally awarded","Small batch & Boutique","Wines only available at cellar door"]'::jsonb,
  winery_signals = '["historic_estate","cellar_door_tasting","private_tasting_room","guided_tasting","barrel_tasting","multi_generation","trophy_winner","gold_medals","view_stunning","cellar_tour","cheese_board","charcuterie_board","dog_friendly","wheelchair_access","accessible_parking","corporate_events","wedding_venue","small_production","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Gralyn Estate is a second-generation, family-owned winery on Caves Road in Wilyabrup, opened in 1975 and home to Margaret River''s first cellar door, with a modern tasting room overlooking the vines. Visitors can taste the full range of premium single-vineyard wines free of charge, and the owners host limited 90-minute premium experiences taking guests from grape to glass and into the original underground cellar to taste museum wines dating back to 1980.',
  famous_for = 'Premium single-vineyard reds and rare aged fortified wines available only at the cellar door; trophy-winning Artizan fortifieds.',
  opening_hours = 'Open daily 10:30am - 4:30pm. Closed Christmas Day, Good Friday and Anzac Day (until midday).',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://gralyn.com.au',
  updated_at = now()
WHERE winery_id = '6878ef0b-b794-39dc-dfec-d6d7200d28e7';

-- Hamelin Bay  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["view_stunning","intimate_welcome","cellar_door_tasting","guided_tasting","winery_lunch","cheese_board","charcuterie_board","child_friendly","seated_tasting","quiet_space","gold_medals","multi_generation","vegetarian","gluten_free","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Established in 1992, Hamelin Bay''s contemporary cellar door opens onto al fresco decking and lawns with a stunning vista of vines, valley, lake and forest over the Five Ashes vineyard. The on-site restaurant serves seasonal lunches built on the freshest local ingredients, Thursday to Sunday, alongside cheese and charcuterie platters daily.',
  famous_for = 'Estate wines from the Five Ashes vineyard (Cabernet Sauvignon, Chardonnay, Sauvignon Blanc, Semillon and Shiraz), enjoyed with a vineyard-view restaurant lunch.',
  opening_hours = 'Open daily 10.30am-4.30pm for wine tasting; small bites and platters daily 11am-4pm; full lunch service Thursday-Sunday 12 noon-2.30pm. Closed Christmas Day, Boxing Day, New Year''s Day and Good Friday.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://hbwines.com.au/',
  updated_at = now()
WHERE winery_id = 'bc30ab2c-95ed-c658-29dd-6d74521e7184';

-- Hayshed Hill  (confidence: high; +12 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Well known Margaret River Name","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","seated_tasting","guided_tasting","blending_experience","wine_chocolate","dog_friendly","halliday_5star","view_stunning","winery_lunch","vegan","corporate_events","wedding_venue","trophy_winner","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Hay Shed Hill is a renowned Wilyabrup cellar door in the Margaret River region, open daily for seated tastings of its estate Chardonnay and Cabernet Sauvignon, with curated experiences including a wine blending session and a wine & chocolate pairing. Its on-site restaurant, Rustico, serves an award-winning shared tapas degustation paired with the estate''s wines.',
  famous_for = 'Chardonnay and Cabernet Sauvignon; named a Top 5 Red Star Winery in the 2025 Halliday Wine Companion.',
  opening_hours = 'Open daily 10am to 5pm. Closed Good Friday, Christmas, Boxing Day, and New Year''s Day (ANZAC Day 2026: 12pm-5pm). Restaurant (Rustico) open Mon-Sun 11am-5pm.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://hayshedhill.com.au',
  updated_at = now()
WHERE winery_id = 'd5df22ab-333e-2eed-e6e1-0c46091d5198';

-- House of Cards  (confidence: high; +11 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Well known Margaret River Name"]'::jsonb,
  winery_signals = '["intimate_welcome","secluded","cellar_door_tasting","garden_picnic","dog_friendly","child_friendly","accommodation","cheese_board","seated_tasting","quiet_space","certified_organic","small_production","view_stunning","winery_lunch","multi_generation","private_tasting_room","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'House of Cards is a certified-organic, single-vineyard winery on iconic Caves Road at the northern end of Margaret River, owned and run by Travis and Elizabeth Wray, where you can enjoy a personal $15 tasting of handcrafted wines while overlooking the natural landscape. On site, Chow''s Table serves modern Chinese and Malay family-style lunches and there''s a cheese-platter offering plus a playground for kids.',
  famous_for = '100% certified-organic, handcrafted single-vineyard wines (bold reds to sparkling whites) from estate fruit',
  opening_hours = 'Cellar door open 7 days a week, 10am - 5pm. Closed Christmas Eve, Christmas Day, Boxing Day & Good Friday. Chow''s Table restaurant open Wednesday - Sunday 12pm - 3pm.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.houseofcardswine.com.au/',
  updated_at = now()
WHERE winery_id = 'd1bf0d17-ae35-b32c-7f8a-be3b7ff4c043';

-- Howard Park  (confidence: high; +17 signals)
UPDATE winery SET
  wine_styles = '["Sparkling & Method traditionnelle Specialist","Well known Margaret River Name","Internationally awarded","Family-owned Estate","Estate-grown fruit only"]'::jsonb,
  winery_signals = '["cellar_door_tasting","garden_picnic","historic_estate","halliday_5star","gold_medals","seated_tasting","vineyard_walk","intimate_welcome","child_friendly","dog_friendly","guided_tasting","private_tasting_room","sunset_tasting","cheese_board","charcuterie_board","corporate_events","press_featured","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Howard Park''s distinctive Cowaramup cellar door is an architecturally designed, Feng Shui-inspired space set among native bushland, with garden lawns, picnic blankets and lawn games where families and dogs are welcome outdoors. Its private Wine Chapel offers an intimate seated experience among chandeliers crafted from 45-year-old vines, paired with local cheese and charcuterie.',
  famous_for = 'Méthode traditionnelle sparkling and estate wines spanning Margaret River and the Great Southern, with a 5-Star Halliday rating and the luxury private Wine Chapel.',
  opening_hours = 'Open daily 10am–5pm',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://howardparkwines.com.au',
  updated_at = now()
WHERE winery_id = '67b423d3-54e3-48fa-3357-6b29bc976ccd';

-- Leeuwin Estate  (confidence: high; +8 signals)
UPDATE winery SET
  wine_styles = '["Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded","Family-owned Estate","Estate-grown fruit only"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","seated_tasting","guided_tasting","winery_lunch","wine_chocolate","vineyard_walk","garden_picnic","intimate_welcome","historic_estate","gold_medals","trophy_winner","press_featured","multi_generation","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Leeuwin Estate is a family-owned Margaret River winery established in 1973 by Denis and Tricia Horgan and now run by three generations of the founding family, built around "The Art of Fine Wine" with an art gallery cellar, curated seated tastings and an acclaimed sit-down restaurant. Its renowned Art Series wines carry labels featuring works by Australian contemporary artists.',
  famous_for = 'Its internationally acclaimed Art Series Chardonnay and the art-and-wine destination experience',
  opening_hours = 'Cellar door open 7 days for tastings, 10:00 AM to 5:00 PM',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://leeuwinestate.com.au/visiting/cellar-door/',
  updated_at = now()
WHERE winery_id = '8023295f-0fda-e61e-8ff9-cf418ffe0f7d';

-- LS Merchants  (confidence: high; +11 signals)
UPDATE winery SET
  wine_styles = '["Small batch & Boutique","Natural & Minimal Intervention","Family-owned Estate","Lesser known (off the beaten track)","Wines only available at cellar door"]'::jsonb,
  winery_signals = '["cellar_door_tasting","dog_friendly","child_friendly","seated_tasting","vineyard_walk","garden_picnic","corporate_events","wedding_venue","blending_experience","picnic_on_estate","byo_food","small_production","gold_medals","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'A boutique Margaret River winery founded by grape explorer Dylan, sourcing small, special parcels of fruit from across Western Australia to craft interesting, approachable and delicious wines. The relaxed cellar door offers seated tastings of 8-10 wines including limited releases and back vintages, with scenic views, a BYO-picnic welcome and a pet-friendly policy.',
  famous_for = 'Hand-crafted, minimal-intervention small-batch wines (notably their Butter Barrels Chardonnay, ranked #1 in the 2026 Top-Up Wines People''s Choice Awards) that showcase the diversity of South West Australian terroir.',
  opening_hours = 'Open 10:30 - 4:30 everyday (the winery''s site states "Open 10:30 - 4:30 everyday"; some external listings note Saturday to 6:00pm)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.lsmerchants.com.au',
  updated_at = now()
WHERE winery_id = 'e831283e-09c2-eaca-e1f3-c2f4f1f41308';

-- Marri Wood Park  (confidence: medium; +8 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Sparkling & Method traditionnelle Specialist","Natural & Minimal Intervention","Small batch & Boutique","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["secluded","cellar_door_tasting","guided_tasting","dog_friendly","child_friendly","intimate_welcome","garden_picnic","quiet_space","cheese_board","vineyard_walk","cellar_tour","certified_organic","regenerative","small_production","gluten_free","vegetarian","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Marri Wood Park is a boutique, family-run Demeter certified biodynamic vineyard established in 1992 in Yallingup, farming sixteen acres of established vines with no chemicals, pesticides, fertiliser or irrigation. Its hand-picked, hand-sorted fruit is fermented in clay amphoras and oak barrels to make small-batch, estate-grown wines.',
  famous_for = 'Demeter certified biodynamic, chemical-free, dry-grown estate wines (including texturally complex skin-contact sauvignon blanc) and a free guided biodynamic vineyard walk with tasting and cheese board.',
  opening_hours = 'Cellar door open Wednesday to Sunday, from 11am (listings cite 11am-3pm). Free guided vineyard tour + tasting + cheese board runs on the last Thursday of each month, by booking, max 8 people.',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://marriwoodpark.com.au',
  updated_at = now()
WHERE winery_id = '5d5bd129-3b5e-bb49-6605-6a6098ba8c72';

-- McHenry Hohnen  (confidence: high; +10 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Natural & Minimal Intervention","Family-owned Estate","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","winery_lunch","cheese_board","garden_picnic","seated_tasting","certified_organic","regenerative","small_production","vegetarian","wine_chocolate","multi_generation","trophy_winner","halliday_5star","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'McHenry Hohnen pairs its cellar door with the Vintners Wine Bar in Witchcliffe, where you can taste biodynamically farmed, single-vineyard wines and settle in for a seasonal, Mediterranean-influenced sharing menu featuring McHenry Farms lamb and estate-grown produce. The setting includes cosy indoor spaces, a garden and a petanque court.',
  famous_for = 'Biodynamic, minimal-intervention single-vineyard wines from family estate vineyards, with a pure expression of Margaret River place.',
  opening_hours = 'Cellar door open seven days a week, 10:30am to 4:30pm. (Vintners Wine Bar full menu Thu-Sun to 10pm; Mon lunch/snacks only.)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.mchenryhohnen.com.au/',
  updated_at = now()
WHERE winery_id = '773a08da-f201-c484-853b-cc5e693bcd5e';

-- Menzies Vineyard  (confidence: high; +13 signals)
UPDATE winery SET
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","intimate_welcome","vineyard_walk","garden_picnic","dog_friendly","guided_tasting","barrel_tasting","cellar_tour","small_production","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'A small, family-owned and operated vineyard on the edge of Wilyabrup, where Robert and Emma Menzies grow estate fruit using high-density planting (vines just one metre apart) and organic principles, all hand-picked and hand-sorted. The cellar door offers a boutique, informative tasting plus a personalised behind-the-scenes tour of the barrel room with Rob.',
  famous_for = 'High-density planted, estate-grown Bordeaux-style reds (Cabernet Sauvignon, Cabernet Franc, Merlot, Malbec) and Chardonnay from a boutique family vineyard.',
  opening_hours = 'Monday to Sunday 11am to 4pm',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://menziesvineyard.com.au',
  updated_at = now()
WHERE winery_id = 'b1222f17-4b74-754c-fa56-5a5bfc96a463';

-- Mr. Barval  (confidence: high; +13 signals)
UPDATE winery SET
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Red Wine Specialist","White Wine Specialist","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","barrel_tasting","winery_lunch","cheese_board","charcuterie_board","vineyard_walk","intimate_welcome","multi_generation","secluded","view_stunning","sunset_tasting","cellar_tour","small_production","child_friendly","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'A relaxed, welcoming cellar door beside Calgardup Brook in Margaret River, framed by forest and vineyard with lake and sunset views, where founder Robert Gherardi pours handcrafted wines emphasising purity of fruit, balance and elegance. Tastings start at $10 for the core range, with a daily "Taste The Tradition" winery tour and grazing platter, plus an Italian-inspired CIBO food van on site.',
  famous_for = 'Old-world, traditional Margaret River winemaking with an Italian influence, particularly Cabernet Sauvignon through the LIRICA label',
  opening_hours = '11.00am to 5pm, seven days a week (closed for tastings Easter Friday and Sunday; CIBO food van operates normally)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://mrbarval.com',
  updated_at = now()
WHERE winery_id = 'c22cbb53-a339-8a7b-6115-3128656645ce';

-- Passel Estate  (confidence: high; +16 signals)
UPDATE winery SET
  wine_styles = '["Small batch & Boutique","Estate-grown fruit only","Red Wine Specialist","Sparkling & Method traditionnelle Specialist","Internationally awarded","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["garden_picnic","dog_friendly","cellar_door_tasting","guided_tasting","seated_tasting","vineyard_walk","charcuterie_board","gold_medals","trophy_winner","halliday_5star","small_production","regenerative","intimate_welcome","secluded","multi_generation","private_tasting_room","sunset_tasting","cheese_board","wine_chocolate","picnic_on_estate","press_featured","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'A small, family-owned Margaret River estate established in 2011 on a property with a bushland conservation sanctuary that protects the critically endangered western ringtail possum. Visits are intimate guided experiences in a dedicated tasting room, ranging from a $10 guided tasting to private nature-and-wine walks, with cheese, charcuterie and chocolate-bonbon pairings.',
  famous_for = 'Sustainably produced, small-quantity wines — especially the trophy-winning ''La Joie'' méthode traditionnelle sparkling Chenin Blanc and award-winning Cabernet Sauvignon.',
  opening_hours = 'Open daily 10:30am–5:00pm (booking recommended). Closed Christmas Day, Boxing Day, New Year''s Day, and Good Friday.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.passelestate.com/visit-our-margaret-river-cellar-door/',
  updated_at = now()
WHERE winery_id = '8d99b646-1362-04a2-9efb-b2e4a0fbbae8';

-- Pierro  (confidence: medium; +15 signals)
UPDATE winery SET
  wine_styles = '["Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","White Wine Specialist","Red Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["intimate_welcome","secluded","dog_friendly","cellar_door_tasting","quiet_space","vineyard_walk","seated_tasting","guided_tasting","cellar_tour","wheelchair_access","step_free_entry","accessible_bathroom","accessible_parking","no_food","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Pierro is a family-operated Willyabrup estate founded by Dr Michael Peterkin, established as one of the original high-density vineyard plantings in Margaret River. The intimate cellar door welcomes visitors to taste and talk through the Pierro range, with personalized vineyard and winery tours offered on Fridays by request.',
  famous_for = 'Exceptional, opulent Margaret River Chardonnay that became a role model for the style',
  opening_hours = 'Open 10-5pm Daily (10am-5pm, 7 days)',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.pierro.com.au',
  updated_at = now()
WHERE winery_id = '786a007c-6447-c792-1c2d-c7eedcb1c80e';

-- Si Vintners  (confidence: medium; +12 signals)
UPDATE winery SET
  wine_styles = '["Natural & Minimal Intervention","Organic & Biodynamic","Estate-grown fruit only","Small batch & Boutique","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","certified_organic","regenerative","small_production","female_winemaker","dog_friendly","wedding_venue","corporate_events","intimate_welcome","secluded","vineyard_walk","guided_tasting","child_friendly","picnic_on_estate","byo_food","no_food","wed","thu","fri","sat"]'::jsonb,
  description = 'A small biodynamic, minimal-intervention estate at Rosa Glen founded in 2010 by husband-and-wife team Sarah Morris and Iwo Jakimowicz, where tastings are intimate and by appointment. Their one-hour Biodynamic Farm Tour & Tasting walks guests through the dry-grown home vineyard and biodynamic vegetable garden before a guided tasting; well-behaved dogs on leads and kids (there is a playground) are welcome.',
  famous_for = 'Natural, DEMETER-certified biodynamic, estate-grown wines that are a true taste of place (the Halcyon Range from old dry-grown home vines, plus the approachable Sauce Range)',
  opening_hours = 'Winery''s own site: tastings by appointment only (booked via Calendly/Humanitix). Regional and Looksi listings state Wednesday to Saturday, 11am-4pm.',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://sivintners.com',
  updated_at = now()
WHERE winery_id = '49e41adf-d8bc-e9ef-9158-f33022a104ce';

-- Skigh Wine  (confidence: medium; +12 signals)
UPDATE winery SET
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique","Estate-grown fruit only","Well known Margaret River Name","Organic & Biodynamic","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["intimate_welcome","garden_picnic","cellar_door_tasting","guided_tasting","quiet_space","small_production","vegan","cheese_board","seated_tasting","barrel_tasting","view_stunning","certified_organic","wedding_venue","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Skigh Wine is a small, boutique Margaret River producer crafting minimal-intervention, natural wines from their organically certified vineyard in the Yallingup Hills, using spontaneous indigenous-yeast ferments and low sulphur. The cellar door is a relaxed converted barn with a sprawling garden, pouring Margaret River classics like Chardonnay and Cabernet alongside alternatives such as Tempranillo, Petit Verdot and Cabernet Franc.',
  famous_for = 'Minimal-intervention natural wines from an organically certified estate vineyard, tasted in a relaxed converted barn.',
  opening_hours = 'Cellar door open 7 days, 10:30am - 5pm, for paid tastings; converted barn with garden, walk-ins welcome but bookings recommended.',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.skighwine.com.au/our-story',
  updated_at = now()
WHERE winery_id = '82dc2053-1d49-5227-9f95-7274a025727a';

-- Stella Bella  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Well known Margaret River Name","Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","guided_tasting","picnic_on_estate","dog_friendly","child_friendly","close_to_town","garden_picnic","quiet_space","gold_medals","trophy_winner","byo_food","no_food","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Stella Bella''s cellar door on Rosa Brook Road, just 4.6km from Margaret River town, offers personalised guided tastings through their southern Margaret River portfolio led by knowledgeable hosts. Visitors can enjoy wine by the glass and bring their own picnic to enjoy in the vineyard surrounds.',
  famous_for = 'Finesse-driven southern Margaret River wines (notably award-winning Chardonnay); six wines in the 2026 Top 100, more than any other WA winery.',
  opening_hours = 'Mon-Sun: 10am to 5pm (closed Good Friday, Christmas Day & Boxing Day)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.stellabella.com.au',
  updated_at = now()
WHERE winery_id = '7097c5db-283a-6e0e-58ad-abd598d233e9';

-- Stormflower  (confidence: high; +16 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Natural & Minimal Intervention","Small batch & Boutique","Estate-grown fruit only","Sparkling & Method traditionnelle Specialist","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["intimate_welcome","cellar_door_tasting","picnic_on_estate","vineyard_walk","certified_organic","small_production","garden_picnic","guided_tasting","seated_tasting","cheese_board","charcuterie_board","dog_friendly","child_friendly","byo_food","trophy_winner","gold_medals","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'A homely, certified-organic cellar door set within the vineyard at Wilyabrup, where you can enjoy guided tastings of small-batch estate wines and relax with a build-your-own cheese and charcuterie platter on picnic rugs in the garden. It is dog friendly, has lawn games and bits for the kids, and welcomes outside food.',
  famous_for = 'Boutique certified-organic Margaret River wines made solely from estate-grown fruit, including small-batch sparkling like Petillant Naturel and Cremant.',
  opening_hours = 'Open 7 days, 11am-5pm',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://stormflower.com.au',
  updated_at = now()
WHERE winery_id = '6be3229f-dc8c-8265-b76f-a0fa486fa504';

-- Vasse Felix  (confidence: high; +15 signals)
UPDATE winery SET
  wine_styles = '["Natural & Minimal Intervention","Family-owned Estate","Estate-grown fruit only","Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["historic_estate","cellar_door_tasting","guided_tasting","winery_lunch","vineyard_walk","cellar_tour","multi_generation","view_stunning","seated_tasting","private_tasting_room","cheese_board","charcuterie_board","vegetarian","vegan","press_featured","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Established in 1967, Vasse Felix is Margaret River''s founding wine estate, home to the region''s original vines and guided by the Holmes a Court family since 1987. Visitors can taste current-vintage wines at the bar, relax in the contemporary Wine Lounge overlooking the Home Vineyard, tour The Vault wine museum, and dine at the acclaimed on-site restaurant.',
  famous_for = 'Margaret River''s founding wine estate (1967), known for Cabernet Sauvignon and Chardonnay including the Heytesbury range.',
  opening_hours = 'Estate open daily 10am - 5pm (cellar door / Wine Lounge); restaurant open daily 12pm - 3pm. Closed Good Friday, Dec 13, Christmas Day and Boxing Day.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.vassefelix.com.au',
  updated_at = now()
WHERE winery_id = '11111111-1111-1111-1111-111111111111';

-- Voyager Estate  (confidence: high; +17 signals)
UPDATE winery SET
  wine_styles = '["Estate-grown fruit only","Organic & Biodynamic","Well known Margaret River Name","Red Wine Specialist","Family-owned Estate","White Wine Specialist","Internationally awarded"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","winery_lunch","vineyard_walk","cellar_tour","garden_picnic","certified_organic","historic_estate","wedding_venue","corporate_events","gold_medals","female_winemaker","seated_tasting","private_tasting_room","wheelchair_access","accessible_parking","accessible_bathroom","step_free_entry","vegetarian","trophy_winner","press_featured","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'One of the founding wine estates of Margaret River, established in 1978 and still family-owned, Voyager Estate is a certified organic producer making 100% estate-grown and made wines, with a celebrated seated restaurant serving a five-course seasonal tasting menu paired with the estate''s wines. Guided tastings in the Wine Room range from the intimate Savour Voyager through to the immersive Discover and Unearth experiences.',
  famous_for = 'World-class Chardonnay and Cabernet Sauvignon from a certified organic, 100% estate-grown estate, plus an award-winning winery restaurant (2025 WA Good Food Guide Regional Restaurant of the Year)',
  opening_hours = 'Wine Room 10am to 5pm Monday to Sunday (bookings recommended); Restaurant 12pm to 5pm Wednesday to Sunday (reservations essential)',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.voyagerestate.com.au',
  updated_at = now()
WHERE winery_id = '81c43507-fd2d-866e-7ce9-b3697ef1bb75';

-- Wills Domain  (confidence: high; +11 signals)
UPDATE winery SET
  wine_styles = '["Well known Margaret River Name","Red Wine Specialist","White Wine Specialist","Sparkling & Method traditionnelle Specialist","Estate-grown fruit only","Internationally awarded","Family-owned Estate"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","guided_tasting","seated_tasting","winery_lunch","cheese_board","charcuterie_board","wedding_venue","corporate_events","dog_friendly","halliday_5star","gold_medals","press_featured","historic_estate","trophy_winner","multi_generation","vegetarian","child_friendly","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Wills Domain is a Haunold family-owned estate in the Gunyulgup Valley at Yallingup, with sun-drenched vineyard views sloping toward the Indian Ocean, a friendly cellar door, and an acclaimed destination restaurant. Two old-vine vineyards established in 1992 supply estate-grown fruit for wines including Cabernet, Shiraz, Chardonnay and estate sparkling.',
  famous_for = 'Its 5 Red Star Halliday rating and multi-hatted fine-dining restaurant, called one of the best fine-dining restaurants in Margaret River.',
  opening_hours = 'Cellar Door open daily 10am-5pm. Restaurant Thursday-Monday 12pm-3pm; cellar door snacks/food 12pm-4pm Thursday-Monday.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://willsdomain.com.au',
  updated_at = now()
WHERE winery_id = '5c8e4e4b-601e-70f2-3c90-3eb9bcacbf3d';

-- Windows Estate  (confidence: high; +11 signals)
UPDATE winery SET
  wine_styles = '["Organic & Biodynamic","Small batch & Boutique","Family-owned Estate","Estate-grown fruit only","Red Wine Specialist","White Wine Specialist","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["cellar_door_tasting","guided_tasting","private_tasting_room","picnic_on_estate","vineyard_walk","cellar_tour","certified_organic","garden_picnic","intimate_welcome","vegetarian","vegan","charcuterie_board","seated_tasting","accommodation","regenerative","small_production","press_featured","thu","fri","sat","sun","mon","tue"]'::jsonb,
  description = 'Windows Estate is a small, certified-organic family vineyard at Yallingup in Margaret River, farming five plots across 15 acres with a focus on biodiversity, regenerative practices and gentle, hand-tended winemaking. Visitors can taste at the intimate cellar door or join an Organic Vineyard Tour & Tasting led by owners Chris or Jo, finishing with a private tasting using Zalto stemware.',
  famous_for = 'Meticulous, detail-driven organic estate winemaking - the Halliday Wine Companion notes "the attention to detail at Windows Estate is second to none."',
  opening_hours = 'Cellar Door open Thursday to Tuesday 10am to 5pm; Wednesday by appointment only.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.windowsestate.com',
  updated_at = now()
WHERE winery_id = '99889e7f-0541-3e5e-9cc9-a0219ec9dcdd';

-- Woodlands  (confidence: high; +9 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","White Wine Specialist","Organic & Biodynamic","Estate-grown fruit only","Well known Margaret River Name","Internationally awarded","Family-owned Estate"]'::jsonb,
  winery_signals = '["cellar_door_tasting","seated_tasting","guided_tasting","cheese_board","charcuterie_board","dog_friendly","child_friendly","garden_picnic","intimate_welcome","gold_medals","multi_generation","certified_organic","historic_estate","trophy_winner","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Founded by David and Heather Watson at Easter 1973, Woodlands is one of Margaret River''s first five vineyards, still family-owned across generations and producing premium Bordeaux-style Cabernet blends and Chardonnay from its certified-organic Wilyabrup estate. The cellar door offers complimentary guided seated tastings of at least 45 minutes alongside a shared grazing board of international cheeses, local charcuterie and house-baked focaccia.',
  famous_for = 'Premium estate-grown Cabernet Sauvignon and Bordeaux-style blends; a pioneering Margaret River family estate.',
  opening_hours = 'Open Monday to Sunday 10am-5pm, last tasting commences at 4pm; cellar door kitchen open 10am-4pm.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://www.woodlandswines.com/',
  updated_at = now()
WHERE winery_id = '44444444-4444-4444-4444-444444444444';

-- Xanadu Wines  (confidence: high; +10 signals)
UPDATE winery SET
  wine_styles = '["Red Wine Specialist","Well known Margaret River Name","Estate-grown fruit only","Internationally awarded","Family-owned Estate"]'::jsonb,
  winery_signals = '["view_stunning","cellar_door_tasting","guided_tasting","private_tasting_room","winery_lunch","cheese_board","charcuterie_board","vineyard_walk","cellar_tour","wedding_venue","seated_tasting","wheelchair_access","gold_medals","trophy_winner","close_to_town","corporate_events","halliday_5star","press_featured","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Xanadu Wines is a family-owned Margaret River estate, established in 1977 and purchased by the Rathbone family in 2005, with a cellar door open daily for tastings overlooking the vineyard and an on-site restaurant pairing southwest produce and Italian traditions with estate wines. Tasting experiences range from the $15 Vinework Tasting to a $50 Museum Flagship Tasting, with cheese and charcuterie boards available.',
  famous_for = 'Internationally awarded Cabernet Sauvignon - its 2023 Cabernet was named Champion Wine of Show at the National Wine Show of Australia and ranked #1 red wine in the world at the International Wine & Spirit Competition.',
  opening_hours = 'Cellar Door open daily 10am-5pm (final tastings poured 4:30pm); closed Christmas Day & Good Friday. Restaurant open for lunch Wednesday to Sunday.',
  data_scraped_at = now(),
  data_confidence = 'high',
  data_source_url = 'https://xanaduwines.com',
  updated_at = now()
WHERE winery_id = '0220379d-36c2-41b8-34e2-762538e27955';

-- Yeah Wine  (confidence: medium; +10 signals)
UPDATE winery SET
  wine_styles = '["Natural & Minimal Intervention","Small batch & Boutique","Family-owned Estate","Lesser known (off the beaten track)"]'::jsonb,
  winery_signals = '["dog_friendly","child_friendly","cellar_door_tasting","small_production","vegan","intimate_welcome","guided_tasting","cellar_tour","mon","tue","wed","thu","fri","sat","sun"]'::jsonb,
  description = 'Yeah Wine is a small-batch, family-owned producer run by Sian and Andrew Dawson, who hand-make, hand-bottle and hand-label over twenty wines sourced from growers across Western Australia. Their rustic cellar door at 401 Wallcliffe Rd is "literally a table and a couple of barrels in the corner of our little winery" - deliberately authentic and unpretentious.',
  famous_for = 'Handmade, minimal-intervention wines (unfined, unfiltered and vegan) championing lesser-known varieties and regions',
  opening_hours = 'Daily 10:30am to 5pm',
  data_scraped_at = now(),
  data_confidence = 'medium',
  data_source_url = 'https://www.yeahwine.com.au',
  updated_at = now()
WHERE winery_id = 'd1239ea2-d792-43c7-06b1-dd65a8b5e269';

COMMIT;
